import type { DshUnifiedRecommendation } from './recommendation.preview-data';

/**
 * UI_PREVIEW_ONLY: Cross-surface journey closure examples.
 * These link Client, Partner, Captain, Field and Operations.
 */
export const DSH_CROSS_SURFACE_JOURNEYS: readonly DshUnifiedRecommendation[] = [
  {
    id: 'journey-discovery',
    surface: 'app-client',
    sourceSurface: 'app-client',
    affectedSurface: 'control-panel',
    actor: 'client',
    lifecycleStep: 'discovery',
    entityId: 'CAT-DISCOVERY',
    entityLabel: 'اكتشاف المتاجر',
    status: 'نشط',
    risk: 'نقص تنوع',
    severity: 'low',
    confidence: 'high',
    affectedEntity: 'واجهة العميل الرئيسية',
    reason: 'يتم عرض المتاجر بناءً على الموقع الجغرافي النشط.',
    evidence: '١٥ متجرًا متاحًا في النطاق الحالي.',
    nextAction: 'تحديث الكتالوج المركزي',
    owner: 'إدارة الكتالوج',
    expectedImpact: 'زيادة نسبة النقر بـ ٢٪',
    primaryActionLabel: 'فتح الكتالوج',
    secondaryActionLabel: 'تعديل الفئات',
    counterpartRouteHint: '/catalogs',
    runtimeBindingStatus: 'UI_PREVIEW_ONLY',
  },
  {
    id: 'journey-checkout',
    surface: 'app-client',
    sourceSurface: 'app-client',
    affectedSurface: 'control-panel',
    actor: 'client',
    lifecycleStep: 'checkout',
    entityId: 'ORD-CLIENT-101',
    entityLabel: 'طلب عميل معلق',
    status: 'بانتظار تأكيد الإسناد',
    risk: 'تأخير محتمل',
    severity: 'high',
    confidence: 'high',
    affectedEntity: 'نورة الفهد',
    reason: 'الطلب تجاوز وقت الإسناد التلقائي بسبب نقص الكباتن في المنطقة.',
    evidence: 'لا يوجد كباتن متاحين ضمن نطاق ٢ كم.',
    nextAction: 'فتح الإسناد اليدوي في لوحة التحكم',
    owner: 'مركز العمليات',
    expectedImpact: 'تقليل وقت الانتظار بـ ٥ دقائق',
    primaryActionLabel: 'فتح الإسناد',
    secondaryActionLabel: 'تنبيه المنطقة',
    counterpartRouteHint: '/operations?workspace=dispatch-assignment&orderId=ORD-CLIENT-101',
    runtimeBindingStatus: 'UI_PREVIEW_ONLY',
  },
  {
    id: 'journey-partner-prep',
    surface: 'app-partner',
    sourceSurface: 'app-partner',
    affectedSurface: 'control-panel',
    actor: 'partner',
    lifecycleStep: 'partner-preparation',
    entityId: 'PRT-902',
    entityLabel: 'متجر الرياض المركزي',
    status: 'ضغط مرتفع',
    risk: 'تأخير في التحضير',
    severity: 'medium',
    confidence: 'medium',
    affectedEntity: 'قائمة الطلبات الجارية',
    reason: 'المتجر لديه ١٥ طلبًا قيد التحضير وسعة المطبخ محدودة.',
    evidence: 'متوسط وقت التحضير زاد بنسبة ٣٠٪.',
    nextAction: 'تقليل نصف قطر الاستلام للمتجر',
    owner: 'إدارة الشركاء',
    expectedImpact: 'موازنة الأحمال ومنع تراكم الطلبات',
    primaryActionLabel: 'تعديل النطاق',
    secondaryActionLabel: 'تواصل مع المتجر',
    counterpartRouteHint: '/partners?id=PRT-902',
    runtimeBindingStatus: 'UI_PREVIEW_ONLY',
  },
  {
    id: 'journey-captain-pickup',
    surface: 'app-captain',
    sourceSurface: 'app-captain',
    affectedSurface: 'control-panel',
    actor: 'captain',
    lifecycleStep: 'pickup',
    entityId: 'CPT-NASSER',
    entityLabel: 'الكابتن ناصر',
    status: 'عائق عند الاستلام',
    risk: 'توقف المسار',
    severity: 'critical',
    confidence: 'high',
    affectedEntity: 'طلب #8822',
    reason: 'الكابتن وصل للمتجر لكن الطلب غير موجود في النظام المحلي للمتجر.',
    evidence: 'رسالة خطأ في الربط التقني للمتجر.',
    nextAction: 'تصعيد الدعم التقني لحل تعارض النظام',
    owner: 'الدعم التشغيلي',
    expectedImpact: 'استئناف المسار خلال ١٠ دقائق',
    primaryActionLabel: 'فتح تذكرة دعم',
    secondaryActionLabel: 'إعادة إسناد الطلب',
    counterpartRouteHint: '/operations?workspace=audit-support-sla&issueId=CPT-NASSER-8822',
    runtimeBindingStatus: 'UI_PREVIEW_ONLY',
  },
  {
    id: 'journey-field-visit',
    surface: 'app-field',
    sourceSurface: 'app-field',
    affectedSurface: 'control-panel',
    actor: 'field',
    lifecycleStep: 'visit',
    entityId: 'FLD-SALEH',
    entityLabel: 'المندوب صالح',
    status: 'زيارة ميدانية نشطة',
    risk: 'تأخير تفعيل',
    severity: 'medium',
    confidence: 'high',
    affectedEntity: 'متجر واحة التمور',
    reason: 'المندوب يقوم بالتحقق من جاهزية المتجر وتدريب الطاقم.',
    evidence: 'تم رفع ٤ صور إثبات جاهزية.',
    nextAction: 'مراجعة الأدلة واعتماد المتجر',
    owner: 'إدارة العمليات الميدانية',
    expectedImpact: 'تفعيل المتجر وبدء استقبال الطلبات',
    primaryActionLabel: 'مراجعة الزيارة',
    secondaryActionLabel: 'تواصل مع المندوب',
    counterpartRouteHint: '/operations?workspace=partner-stores&storeId=OASIS-01',
    runtimeBindingStatus: 'UI_PREVIEW_ONLY',
  },
  {
    id: 'journey-onboarding',
    surface: 'app-field',
    sourceSurface: 'app-field',
    affectedSurface: 'control-panel',
    actor: 'field',
    lifecycleStep: 'onboarding',
    entityId: 'ONB-998',
    entityLabel: 'تهيئة شريك جديد',
    status: 'بانتظار البيانات',
    risk: 'عدم اكتمال الملف',
    severity: 'low',
    confidence: 'medium',
    affectedEntity: 'مطعم مذاق الشرق',
    reason: 'المتجر لم يرفع السجل التجاري أو لقطة القائمة.',
    evidence: 'حقول البيانات الإلزامية فارغة.',
    nextAction: 'إرسال تنبيه للمتجر عبر التطبيق',
    owner: 'فريق التفعيل',
    expectedImpact: 'إكمال الطلب خلال ٢٤ ساعة',
    primaryActionLabel: 'فتح ملف الشريك',
    secondaryActionLabel: 'إرسال تنبيه',
    counterpartRouteHint: '/partners?onboardingId=ONB-998',
    runtimeBindingStatus: 'UI_PREVIEW_ONLY',
  },
  {
    id: 'journey-delivery-tracking',
    surface: 'app-captain',
    sourceSurface: 'app-captain',
    affectedSurface: 'app-client',
    actor: 'captain',
    lifecycleStep: 'delivery',
    entityId: 'ORD-DLV-554',
    entityLabel: 'توصيل جارٍ',
    status: 'في الطريق للعميل',
    risk: 'تأخير طفيف',
    severity: 'low',
    confidence: 'high',
    affectedEntity: 'أحمد سعيد',
    reason: 'الكابتن يتحرك باتجاه موقع العميل بعد استلام الطلب بنجاح.',
    evidence: 'موقع GPS حي وتحديث حالة مباشر.',
    nextAction: 'متابعة الوصول وتسليم الإثبات',
    owner: 'نظام التتبع',
    expectedImpact: 'تحديث وقت الوصول المتوقع',
    primaryActionLabel: 'فتح التتبع',
    secondaryActionLabel: 'تواصل مع العميل',
    counterpartRouteHint: '/app-client/orders?id=ORD-DLV-554',
    runtimeBindingStatus: 'UI_PREVIEW_ONLY',
  },
];
