import type { DshUnifiedRecommendation } from './dshRecommendationModel';

/**
 * UI_PREVIEW_ONLY: Cross-surface journey closure examples.
 * These link Client, Partner, Captain and Operations.
 */
export const DSH_CROSS_SURFACE_JOURNEYS: readonly DshUnifiedRecommendation[] = [
  {
    id: 'journey-client-to-ops',
    surface: 'app-client',
    sourceSurface: 'app-client',
    affectedSurface: 'control-panel',
    actor: 'client',
    lifecycleStep: 'checkout',
    entityId: 'ORD-CLIENT-101',
    entityLabel: 'طلب عميل معلق',
    status: 'بانتظار تأكيد الإسناد',
    risk: 'تأخير محتمل',
    severity: 'high',
    confidence: 'high',
    affectedEntity: 'نورة الفهد',
    reason: 'الطلب تجاوز وقت الإسناد التلقائي بسبب نقص الكباتن في المنطقة.',
    evidence: 'لا يوجد كباتن متاحين ضمن نطاق ٢ كم.',
    nextAction: 'فتح الإسناد اليدوي في لوحة التحكم',
    owner: 'مركز العمليات',
    expectedImpact: 'تقليل وقت الانتظار بـ ٥ دقائق',
    primaryActionLabel: 'فتح الإسناد',
    secondaryActionLabel: 'تنبيه المنطقة',
    counterpartRouteHint: '/operations?workspace=dispatch-assignment&orderId=ORD-CLIENT-101',
    runtimeBindingStatus: 'UI_PREVIEW_ONLY',
  },
  {
    id: 'journey-ops-to-partner',
    surface: 'control-panel',
    sourceSurface: 'control-panel',
    affectedSurface: 'app-partner',
    actor: 'operator',
    lifecycleStep: 'operations-intervention',
    entityId: 'PRT-902',
    entityLabel: 'متجر الرياض المركزي',
    status: 'ضغط مرتفع',
    risk: 'تأخير في التحضير',
    severity: 'medium',
    confidence: 'medium',
    affectedEntity: 'قائمة الطلبات الجارية',
    reason: 'المتجر لديه ١٥ طلبًا قيد التحضير وسعة المطبخ محدودة.',
    evidence: 'متوسط وقت التحضير زاد بنسبة ٣٠٪.',
    nextAction: 'تقليل نصف قطر الاستلام للمتجر',
    owner: 'إدارة الشركاء',
    expectedImpact: 'موازنة الأحمال ومنع تراكم الطلبات',
    primaryActionLabel: 'تعديل النطاق',
    secondaryActionLabel: 'تواصل مع المتجر',
    counterpartRouteHint: '/app-partner/orders?focus=pressure',
    runtimeBindingStatus: 'UI_PREVIEW_ONLY',
  },
  {
    id: 'journey-captain-to-ops',
    surface: 'app-captain',
    sourceSurface: 'app-captain',
    affectedSurface: 'control-panel',
    actor: 'captain',
    lifecycleStep: 'pickup',
    entityId: 'CPT-NASSER',
    entityLabel: 'الكابتن ناصر',
    status: 'عائق عند الاستلام',
    risk: 'توقف المسار',
    severity: 'critical',
    confidence: 'high',
    affectedEntity: 'طلب #8822',
    reason: 'الكابتن وصل للمتجر لكن الطلب غير موجود في النظام المحلي للمتجر.',
    evidence: 'رسالة خطأ في الربط التقني للمتجر.',
    nextAction: 'تصعيد الدعم التقني لحل تعارض النظام',
    owner: 'الدعم التشغيلي',
    expectedImpact: 'استئناف المسار خلال ١٠ دقائق',
    primaryActionLabel: 'فتح تذكرة دعم',
    secondaryActionLabel: 'إعادة إسناد الطلب',
    counterpartRouteHint: '/operations?workspace=audit-support-sla&issueId=CPT-NASSER-8822',
    runtimeBindingStatus: 'UI_PREVIEW_ONLY',
  },
];
