import type { DshCaptainRouteId } from './dsh-captain.routes';

export type DshCaptainRegistryRouteId = DshCaptainRouteId | 'wlt-dsh-captain-finance-bridge';

export type DshCaptainScreenRegistryItem = {
  readonly screenId: string;
  readonly routeId: DshCaptainRegistryRouteId;
  readonly surfaceId: 'app-captain';
  readonly ownerKind: 'app' | 'service' | 'integration';
  readonly ownerId: 'app-captain' | 'dsh' | 'wlt.dsh';
  readonly serviceId?: 'dsh' | 'wlt';
  readonly linkedServiceId?: 'dsh' | 'wlt';
  readonly ownerPath: string;
  readonly componentName: string;
  readonly screenKind: 'TAB_ROOT' | 'SCREEN_ENTRY' | 'FLOW_STEP' | 'MODAL' | 'SHEET';
  readonly flowId?: string;
  readonly requiredStates: readonly ('loading' | 'empty' | 'error' | 'success' | 'offline' | 'disabled' | 'retry' | 'blocked')[];
  readonly requiredPermissions?: readonly ('location' | 'notifications' | 'camera' | 'mediaLibrary')[];
  readonly analytics: {
    readonly screenView: string;
  };
  readonly deepLinkPath?: string;
  readonly fallbackRouteId?: DshCaptainRouteId;
  readonly releaseCriticality: 'P0' | 'P1' | 'P2';
  readonly status: 'TBD' | 'UNPROVEN' | 'VERIFIED' | 'CLOSED' | 'DEPRECATED';
};

export const dshCaptainScreenRegistry = [
  {
    screenId: 'captain.dsh.home.dashboard',
    routeId: 'dsh-captain-home',
    surfaceId: 'app-captain',
    ownerKind: 'app',
    ownerId: 'app-captain',
    serviceId: 'dsh',
    ownerPath: 'dsh/frontend/app-captain/DshCaptainSurface.tsx',
    componentName: 'DshCaptainSurface',
    screenKind: 'TAB_ROOT',
    flowId: 'captain.dsh.home',
    requiredStates: ['success', 'offline'],
    analytics: { screenView: 'captain_dsh_home_dashboard_view' },
    deepLinkPath: '/captain/dsh',
    fallbackRouteId: 'dsh-captain-home',
    releaseCriticality: 'P1',
    status: 'VERIFIED',
  },
  {
    screenId: 'captain.dsh.entry',
    routeId: 'dsh-captain-entry',
    surfaceId: 'app-captain',
    ownerKind: 'service',
    ownerId: 'dsh',
    serviceId: 'dsh',
    ownerPath: 'dsh/frontend/app-captain/screens/DshCaptainEntryScreen.tsx',
    componentName: 'DshEntryScreen',
    screenKind: 'SCREEN_ENTRY',
    flowId: 'captain.dsh.entry',
    requiredStates: ['loading', 'empty', 'error', 'success'],
    analytics: { screenView: 'captain_dsh_entry_view' },
    fallbackRouteId: 'dsh-captain-home',
    releaseCriticality: 'P1',
    status: 'VERIFIED',
  },
  {
    screenId: 'captain.dsh.orders.inbox',
    routeId: 'dsh-captain-inbox',
    surfaceId: 'app-captain',
    ownerKind: 'service',
    ownerId: 'dsh',
    serviceId: 'dsh',
    ownerPath: 'dsh/frontend/app-captain/screens/DshCaptainOrdersScreen.tsx',
    componentName: 'CaptainOrdersInboxScreen',
    screenKind: 'SCREEN_ENTRY',
    flowId: 'captain.dsh.orders',
    requiredStates: ['loading', 'empty', 'error', 'success'],
    analytics: { screenView: 'captain_dsh_orders_inbox_view' },
    fallbackRouteId: 'dsh-captain-entry',
    releaseCriticality: 'P0',
    status: 'VERIFIED',
  },
  {
    screenId: 'captain.dsh.orders.detail',
    routeId: 'dsh-captain-detail',
    surfaceId: 'app-captain',
    ownerKind: 'service',
    ownerId: 'dsh',
    serviceId: 'dsh',
    ownerPath: 'dsh/frontend/app-captain/screens/DshCaptainOrdersScreen.tsx',
    componentName: 'CaptainOrderDetailScreen',
    screenKind: 'FLOW_STEP',
    flowId: 'captain.dsh.orders',
    requiredStates: ['error', 'success', 'retry'],
    analytics: { screenView: 'captain_dsh_order_detail_view' },
    fallbackRouteId: 'dsh-captain-inbox',
    releaseCriticality: 'P0',
    status: 'VERIFIED',
  },
  {
    screenId: 'captain.dsh.orders.chat',
    routeId: 'dsh-captain-order-chat',
    surfaceId: 'app-captain',
    ownerKind: 'service',
    ownerId: 'dsh',
    serviceId: 'dsh',
    ownerPath: 'dsh/frontend/app-captain/screens/DshCaptainOrdersScreen.tsx',
    componentName: 'DshCaptainOrderChatScreen',
    screenKind: 'FLOW_STEP',
    flowId: 'captain.dsh.orders.chat',
    requiredStates: ['error', 'success', 'retry'],
    analytics: { screenView: 'captain_dsh_order_chat_view' },
    fallbackRouteId: 'dsh-captain-detail',
    releaseCriticality: 'P1',
    status: 'VERIFIED',
  },
  {
    screenId: 'captain.dsh.orders.bell',
    routeId: 'dsh-captain-bell',
    surfaceId: 'app-captain',
    ownerKind: 'service',
    ownerId: 'dsh',
    serviceId: 'dsh',
    ownerPath: 'dsh/frontend/app-captain/screens/DshCaptainOrdersScreen.tsx',
    componentName: 'DshCaptainBellScreen',
    screenKind: 'MODAL',
    flowId: 'captain.dsh.orders',
    requiredStates: ['loading', 'empty', 'error', 'success'],
    analytics: { screenView: 'captain_dsh_bell_view' },
    fallbackRouteId: 'dsh-captain-inbox',
    releaseCriticality: 'P1',
    status: 'VERIFIED',
  },
  {
    screenId: 'captain.dsh.support.directory',
    routeId: 'dsh-captain-support-directory',
    surfaceId: 'app-captain',
    ownerKind: 'service',
    ownerId: 'dsh',
    serviceId: 'dsh',
    ownerPath: 'dsh/frontend/app-captain/screens/DshCaptainOperationsScreen.tsx',
    componentName: 'DshCaptainSupportDirectoryScreen',
    screenKind: 'FLOW_STEP',
    flowId: 'captain.dsh.operations',
    requiredStates: ['error', 'success', 'retry'],
    analytics: { screenView: 'captain_dsh_support_directory_view' },
    fallbackRouteId: 'dsh-captain-home',
    releaseCriticality: 'P1',
    status: 'VERIFIED',
  },
  {
    screenId: 'captain.dsh.support.workspace',
    routeId: 'dsh-captain-support-screen',
    surfaceId: 'app-captain',
    ownerKind: 'service',
    ownerId: 'dsh',
    serviceId: 'dsh',
    ownerPath: 'dsh/frontend/app-captain/DshCaptainSurface.tsx',
    componentName: 'DshCaptainSurface',
    screenKind: 'FLOW_STEP',
    flowId: 'captain.dsh.operations',
    requiredStates: ['error', 'success', 'retry'],
    analytics: { screenView: 'captain_dsh_support_workspace_view' },
    fallbackRouteId: 'dsh-captain-support-directory',
    releaseCriticality: 'P1',
    status: 'VERIFIED',
  },
  {
    screenId: 'captain.dsh.account.root',
    routeId: 'dsh-captain-account',
    surfaceId: 'app-captain',
    ownerKind: 'app',
    ownerId: 'app-captain',
    serviceId: 'dsh',
    ownerPath: 'dsh/frontend/app-captain/DshCaptainSurface.tsx',
    componentName: 'DshCaptainSurface',
    screenKind: 'TAB_ROOT',
    flowId: 'captain.dsh.account',
    requiredStates: ['success'],
    analytics: { screenView: 'captain_dsh_account_root_view' },
    fallbackRouteId: 'dsh-captain-home',
    releaseCriticality: 'P2',
    status: 'VERIFIED',
  },
  {
    screenId: 'captain.dsh.account.profile',
    routeId: 'dsh-captain-account-profile',
    surfaceId: 'app-captain',
    ownerKind: 'service',
    ownerId: 'dsh',
    serviceId: 'dsh',
    ownerPath: 'dsh/frontend/app-captain/screens/DshCaptainProfileScreen.tsx',
    componentName: 'DshCaptainProfileGetScreen',
    screenKind: 'FLOW_STEP',
    flowId: 'captain.dsh.account',
    requiredStates: ['loading', 'empty', 'error', 'success'],
    analytics: { screenView: 'captain_dsh_account_profile_view' },
    fallbackRouteId: 'dsh-captain-account',
    releaseCriticality: 'P2',
    status: 'VERIFIED',
  },
  {
    screenId: 'captain.dsh.account.finance',
    routeId: 'dsh-captain-account-finance',
    surfaceId: 'app-captain',
    ownerKind: 'integration',
    ownerId: 'wlt.dsh',
    serviceId: 'wlt',
    linkedServiceId: 'dsh',
    ownerPath: 'dsh/frontend/app-captain/screens/DshCaptainFinanceScreen.tsx',
    componentName: 'DshCaptainCodBalanceScreen',
    screenKind: 'FLOW_STEP',
    flowId: 'captain.dsh.account',
    requiredStates: ['loading', 'empty', 'error', 'success'],
    analytics: { screenView: 'captain_dsh_account_finance_view' },
    fallbackRouteId: 'dsh-captain-account',
    releaseCriticality: 'P2',
    status: 'VERIFIED',
  },
  {
    screenId: 'captain.dsh.account.orders',
    routeId: 'dsh-captain-account-orders',
    surfaceId: 'app-captain',
    ownerKind: 'service',
    ownerId: 'dsh',
    serviceId: 'dsh',
    ownerPath: 'dsh/frontend/app-captain/DshCaptainSurface.tsx',
    componentName: 'DshCaptainSurface',
    screenKind: 'FLOW_STEP',
    flowId: 'captain.dsh.account',
    requiredStates: ['success'],
    analytics: { screenView: 'captain_dsh_account_orders_view' },
    fallbackRouteId: 'dsh-captain-account',
    releaseCriticality: 'P1',
    status: 'VERIFIED',
  },
  {
    screenId: 'captain.dsh.account.docs',
    routeId: 'dsh-captain-account-docs',
    surfaceId: 'app-captain',
    ownerKind: 'app',
    ownerId: 'app-captain',
    serviceId: 'dsh',
    ownerPath: 'dsh/frontend/app-captain/DshCaptainSurface.tsx',
    componentName: 'DshCaptainSurface',
    screenKind: 'FLOW_STEP',
    flowId: 'captain.dsh.account',
    requiredStates: ['success'],
    analytics: { screenView: 'captain_dsh_account_docs_view' },
    fallbackRouteId: 'dsh-captain-account',
    releaseCriticality: 'P2',
    status: 'VERIFIED',
  },
  {
    screenId: 'captain.dsh.account.shifts',
    routeId: 'dsh-captain-account-shifts',
    surfaceId: 'app-captain',
    ownerKind: 'app',
    ownerId: 'app-captain',
    serviceId: 'dsh',
    ownerPath: 'dsh/frontend/app-captain/DshCaptainSurface.tsx',
    componentName: 'DshCaptainSurface',
    screenKind: 'FLOW_STEP',
    flowId: 'captain.dsh.account',
    requiredStates: ['success'],
    analytics: { screenView: 'captain_dsh_account_shifts_view' },
    fallbackRouteId: 'dsh-captain-account',
    releaseCriticality: 'P2',
    status: 'VERIFIED',
  },
  {
    screenId: 'captain.dsh.account.support',
    routeId: 'dsh-captain-account-support',
    surfaceId: 'app-captain',
    ownerKind: 'app',
    ownerId: 'app-captain',
    serviceId: 'dsh',
    ownerPath: 'dsh/frontend/app-captain/DshCaptainSurface.tsx',
    componentName: 'DshCaptainSurface',
    screenKind: 'FLOW_STEP',
    flowId: 'captain.dsh.account',
    requiredStates: ['success'],
    analytics: { screenView: 'captain_dsh_account_support_view' },
    fallbackRouteId: 'dsh-captain-account',
    releaseCriticality: 'P2',
    status: 'VERIFIED',
  },
  {
    screenId: 'captain.wlt.dsh.finance.bridge',
    routeId: 'wlt-dsh-captain-finance-bridge',
    surfaceId: 'app-captain',
    ownerKind: 'integration',
    ownerId: 'wlt.dsh',
    serviceId: 'wlt',
    linkedServiceId: 'dsh',
    ownerPath: 'wlt/frontend/app-captain/dsh/WltDshCaptainBridge.tsx',
    componentName: 'WltDshCaptainBridge',
    screenKind: 'FLOW_STEP',
    flowId: 'captain.dsh.finance',
    requiredStates: ['loading', 'empty', 'error', 'success', 'offline', 'blocked'],
    analytics: { screenView: 'captain_wlt_dsh_finance_bridge_view' },
    fallbackRouteId: 'dsh-captain-account-finance',
    releaseCriticality: 'P0',
    status: 'VERIFIED',
  },
  {
    screenId: 'captain.dsh.orders.pickup-dropoff',
    routeId: 'dsh-captain-pickup-dropoff',
    surfaceId: 'app-captain',
    ownerKind: 'app',
    ownerId: 'app-captain',
    serviceId: 'dsh',
    ownerPath: 'dsh/frontend/app-captain/screens/DshCaptainPickupDropoffScreen.tsx',
    componentName: 'DshCaptainPickupDropoffScreen',
    screenKind: 'FLOW_STEP',
    flowId: 'captain.dsh.orders',
    requiredStates: ['success'],
    analytics: { screenView: 'captain_dsh_orders_pickup_dropoff_view' },
    fallbackRouteId: 'dsh-captain-inbox',
    releaseCriticality: 'P1',
    status: 'READY_FOR_REVIEW',
  },
  {
    screenId: 'captain.dsh.orders.pod-submission',
    routeId: 'dsh-captain-pod-submission',
    surfaceId: 'app-captain',
    ownerKind: 'app',
    ownerId: 'app-captain',
    serviceId: 'dsh',
    ownerPath: 'dsh/frontend/app-captain/screens/DshCaptainPoDSubmissionScreen.tsx',
    componentName: 'DshCaptainPoDSubmissionScreen',
    screenKind: 'FLOW_STEP',
    flowId: 'captain.dsh.orders',
    requiredStates: ['loading', 'success', 'error'],
    analytics: { screenView: 'captain_dsh_orders_pod_submission_view' },
    fallbackRouteId: 'dsh-captain-inbox',
    releaseCriticality: 'P1',
    status: 'READY_FOR_REVIEW',
  },
] as const satisfies readonly DshCaptainScreenRegistryItem[];
