export const dshAppClientFamilyOrder = [
  'entry',
  'home',
  'discovery',
  'stores',
  'categories',
  'cart',
  'checkout',
  'orders',
  'tracking',
  'favorites',
  'support',
  'loyalty',
  'awnak',
  'gas',
  'shein',
] as const;

export const dshAppClientRouteFamilyCatalog = {
  home: 'home',
  entry: 'entry',
  'stores-list': 'stores',
  'store-detail': 'stores',
  'store-items': 'stores',
  'store-items-list': 'stores',
  'awnak-order-create': 'awnak',
  'cart-get': 'cart',
  'cart-init': 'cart',
  'cart-item-add': 'cart',
  'cart-item-remove': 'cart',
  'cart-item-update': 'cart',
  'categories-list': 'categories',
  'category-get': 'categories',
  'favorite-toggle': 'favorites',
  'favorites-list': 'favorites',
  search: 'discovery',
  'store-get': 'stores',
  'create-order': 'checkout',
  review: 'checkout',
  'checkout-workspace': 'checkout',
  benefits: 'loyalty',
  'conversation-workspace': 'support',
  'delivery-management-workspace': 'tracking',
  'intake-workspace': 'checkout',
  'listing-status-update': 'support',
  'order-issue-workspace': 'support',
  'proxy-workspace': 'support',
  'shein-order-create': 'shein',
  'service-settings': 'support',
  'trust-workspace': 'support',
  'zone-set': 'support',
  'support-directory': 'support',
  'support-screen': 'support',
  success: 'orders',
  'orders-list': 'orders',
  tracking: 'tracking',
} as const;

export const dshAppClientSupportScreenFamilyCatalog = {
  'awnak-order-create': 'awnak',
  'booking-create': 'checkout',
  'chat-read-ack': 'support',
  'chat-send': 'support',
  'checkout-gate': 'checkout',
  'delivery-attempt-create': 'tracking',
  'delivery-attempts-list': 'tracking',
  'delivery-close': 'tracking',
  'delivery-eta-get': 'tracking',
  'delivery-get': 'orders',
  'delivery-reassign': 'tracking',
  'delivery-track-get': 'tracking',
  'entitlements-get': 'loyalty',
  'estimate-create': 'checkout',
  'estimate-get': 'checkout',
  'external-order-create': 'checkout',
  'gas-refill-order-create': 'gas',
  'listing-status-update': 'support',
  'loyalty-points-redeem': 'loyalty',
  'loyalty-points-user-balance': 'loyalty',
  'loyalty-points-user-history': 'loyalty',
  'order-accept': 'orders',
  'order-cancel': 'orders',
  'order-complete': 'orders',
  'order-create': 'checkout',
  'order-escrow-hold': 'support',
  'order-escrow-release': 'support',
  'order-get': 'orders',
  'order-issue-flag': 'support',
  'order-proof-code-generate': 'support',
  'order-proof-verify': 'support',
  'order-rate': 'orders',
  'order-receipt-get': 'orders',
  'order-status-get': 'tracking',
  'order-status-update': 'tracking',
  'pricing-preview': 'checkout',
  'pricing-snapshot-get': 'checkout',
  'promo-apply': 'checkout',
  'proxy-request-create': 'support',
  'proxy-request-approve': 'support',
  'proxy-request-review': 'support',
  'proxy-request-reject': 'support',
  'proxy-request-tracking': 'support',
  'review-create': 'support',
  'reviews-list': 'support',
  'service-modes-resolve': 'support',
  'subscription-family-get': 'loyalty',
  'subscription-family-members-get': 'loyalty',
  'subscription-family-members-post': 'loyalty',
  'subscription-pro-catalog': 'loyalty',
  'subscription-sync': 'loyalty',
  'subscription-tier-get': 'loyalty',
  'subscription-upgrade-post': 'loyalty',
  'zone-set': 'support',
} as const;

export type DshAppClientFamilyId = (typeof dshAppClientFamilyOrder)[number];