import type { Phase12FixtureLocation } from '../types';

export const dshAppClientFixtureLocations: Phase12FixtureLocation[] = [
  {
    candidateId: 'dsh_client_entry_discovery_home',
    canonicalTarget: 'dsh_client_entry_discovery_home',
    surface: 'app-client',
    phase: 'Phase 12',
    mode: 'fixtures-only',
    location: 'packages/surfaces/src/dsh/app-client/dsh_client_entry_discovery_home/fixtures',
    status: 'declared',
  },
  {
    candidateId: 'dsh_client_category_or_store_detail',
    canonicalTarget: 'dsh_client_category_or_store_detail',
    surface: 'app-client',
    phase: 'Phase 12',
    mode: 'fixtures-only',
    location: 'packages/surfaces/src/dsh/app-client/dsh_client_category_or_store_detail/fixtures',
    status: 'declared',
  },
  {
    candidateId: 'dsh_client_cart_review',
    canonicalTarget: 'dsh_client_cart_review',
    surface: 'app-client',
    phase: 'Phase 12',
    mode: 'fixtures-only',
    location: 'packages/surfaces/src/dsh/app-client/dsh_client_cart_review/fixtures',
    status: 'declared',
  },
  {
    candidateId: 'dsh_client_checkout_confirm',
    canonicalTarget: 'dsh_client_checkout_confirm',
    surface: 'app-client',
    phase: 'Phase 12',
    mode: 'fixtures-only',
    location: 'packages/surfaces/src/dsh/app-client/dsh_client_checkout_confirm/fixtures',
    status: 'declared',
  },
  {
    candidateId: 'dsh_client_active_order_tracking',
    canonicalTarget: 'dsh_client_active_order_tracking',
    surface: 'app-client',
    phase: 'Phase 12',
    mode: 'fixtures-only',
    location: 'packages/surfaces/src/dsh/app-client/dsh_client_active_order_tracking/fixtures',
    status: 'declared',
  },
  {
    candidateId: 'dsh_client_proxy_request_entry',
    canonicalTarget: 'dsh_client_proxy_request_entry',
    surface: 'app-client',
    phase: 'Phase 12',
    mode: 'fixtures-only',
    location: 'packages/surfaces/src/dsh/app-client/dsh_client_proxy_request_entry/fixtures',
    status: 'declared',
  },
  {
    candidateId: 'dsh_client_proxy_request_tracking',
    canonicalTarget: 'dsh_client_proxy_request_tracking',
    surface: 'app-client',
    phase: 'Phase 12',
    mode: 'fixtures-only',
    location: 'packages/surfaces/src/dsh/app-client/dsh_client_proxy_request_tracking/fixtures',
    status: 'declared',
  },
];