export const surfaceCatalog = [
  'home',
  'entry',
  'stores-list',
  'store-detail',
  'store-items',
  'cart-get',
  'cart-init',
  'cart-item-add',
  'cart-item-remove',
  'cart-item-update',
  'categories-list',
  'category-get',
  'favorite-toggle',
  'favorites-list',
  'home-get',
  'search',
  'store-get',
  'create-order',
  'review',
  'tracking',
  'orders-list',
  'success',
  '_flow-id_'
] as const;
