/**
 * UI_PREVIEW_ONLY: not runtime truth, not backend/API/binding source.
 */
export const operationsPreviewDataContract = {
  dataKind: 'UI_PREVIEW_ONLY',
  runtimeTruth: false,
  backendSource: false,
  bindingSource: false,
  timezoneSemantics: 'preview-only local display / not runtime UTC source',
  moneySemantics: 'preview-only display values / not accounting source',
} as const;

export const OPERATIONS_PULSE_METRICS = [
  { id: 'command-center-open-orders', title: 'الطلبات المفتوحة', value: '128', description: 'الطلبات التي تتحرك داخل غرفة العمليات.', tone: 'brand' },
  { id: 'command-center-dispatch-risk', title: 'مخاطر الإسناد', value: '9', description: 'طلبات تحتاج إسنادًا يدويًا الآن.', tone: 'warning' },
  { id: 'command-center-captain-cover', title: 'تغطية الكباتن', value: '42', description: 'الكباتن المتاحون ظاهرون الآن.', tone: 'best' },
  { id: 'command-center-escalations', title: 'الاستثناءات', value: '17', description: 'استثناءات مفتوحة تنتظر مالكًا.', tone: 'danger' },
] as const;

export const LIVE_ORDERS_OPERATIONAL_PREVIEW = {
  summary: {
    awaitingAcknowledgement: 3,
    blockedRings: 2,
    ringLabel: 'تنبيه الوصول',
    actionHint: 'أعد الرنين ثم افتح الإسناد إذا بقي الطلب بلا رد.',
  },
  rows: [
    {
      id: 'LO-1024',
      status: 'قيد الإسناد',
      statusTone: 'warning',
      eta: '12 دقيقة',
      destination: 'متجر الرياض',
      captain: 'غير مسند',
      notes: 'الطلب ينتظر قرار الإسناد قبل أول رنين.',
      ringLabel: 'لم يؤكد الوصول',
      actionHint: 'أعد الرنين ثم افحص التغطية.',
      arrivalTimeline: ['قيد الوصول', 'الرنين الأول لم يؤكد', 'بانتظار رد مالك القرار'],
      actionPlans: ['افتح الإسناد', 'أرسل رنينًا جديدًا', 'صعّد للمشرف إذا بقي بلا مالك'],
      suggestion: {
        label: 'افتح الإسناد فورًا',
        reason: 'الطلب بلا كابتن والتأخير يتزايد.',
        confidence: 'high',
        action: 'فتح الإسناد',
        secondary: 'تواصل مع الدعم',
        auditRequired: false,
      },
    },
    {
      id: 'LO-1077',
      status: 'بانتظار إثبات',
      statusTone: 'danger',
      eta: '18 دقيقة',
      destination: 'مقهى الشرق',
      captain: 'خالد',
      notes: 'النقل متوقف حتى يصل إثبات الاستلام.',
      ringLabel: 'محجوب',
      actionHint: 'اطلب إثباتًا قبل الإغلاق.',
      arrivalTimeline: ['وصل الطلب', 'الرنين محجوب', 'الإثبات مطلوب قبل الإغلاق'],
      actionPlans: ['اطلب الإثبات', 'افتح الدعم', 'احتفظ بالسجل'],
      suggestion: {
        label: 'اطلب الإثبات الآن',
        reason: 'الإثبات مفقود والحل مرهون بالدعم.',
        confidence: 'high',
        action: 'طلب الإثبات',
        secondary: 'فتح الدعم',
        auditRequired: true,
      },
    },
    {
      id: 'LO-1099',
      status: 'في الطريق',
      statusTone: 'best',
      eta: '7 دقائق',
      destination: 'مخبز الورد',
      captain: 'سلمان',
      notes: 'النافذة ما زالت آمنة والتسليم قريب.',
      ringLabel: 'تنبيه الوصول',
      actionHint: 'راقب ETA ولا تصعيد الآن.',
      arrivalTimeline: ['الكابتن في الطريق', 'النافذة ما زالت آمنة', 'التسليم قريب'],
      actionPlans: ['راقب ETA', 'لا تصعيد الآن', 'افتح التفاصيل إذا تأخر'],
      suggestion: {
        label: 'تابع وقت التسليم',
        reason: 'الطلب في المسار الطبيعي ولا يحتاج تدخلًا الآن.',
        confidence: 'medium',
        action: 'مراقبة ETA',
        secondary: 'فتح التفاصيل',
        auditRequired: false,
      },
    },
  ] as const,
} as const;

export const DISPATCH_ASSIGNMENT_OPERATIONAL_PREVIEW = {
  summary: {
    waitingAssignment: 6,
    availableCaptains: 4,
    readyForPickup: 3,
    dispatchBlockers: 2,
  },
  rows: [
    {
      id: 'DA-2001',
      status: 'طلبات بانتظار الإسناد',
      statusTone: 'warning',
      captain: 'سعد م.',
      distance: '1.2 كم',
      pickupEta: '5 دقائق',
      dropoffEta: '19 دقيقة',
      confidence: 'ثقة عالية',
      blocker: 'لا يوجد',
      readyForPickup: 'جاهز لمسار الاستلام',
      recommendation: 'أسند إلى سعد م. الآن',
      note: 'الأقرب والمتاح حاليًا.',
      actionPlans: ['تأكيد الإسناد', 'مراقبة الاستلام', 'تخفيف ضغط التوزيع'],
    },
    {
      id: 'DA-2002',
      status: 'يحتاج إعادة إسناد',
      statusTone: 'brand',
      captain: 'محمد ع.',
      distance: '0.8 كم',
      pickupEta: '2 دقيقة',
      dropoffEta: '16 دقيقة',
      confidence: 'ثقة عالية',
      blocker: 'أول كابتن رفض',
      readyForPickup: 'جاهز بعد إعادة التعيين',
      recommendation: 'أعد الإسناد لمحمد ع.',
      note: 'بديل أفضل مع وقت استجابة أقل.',
      actionPlans: ['إعادة التعيين', 'تخطي الرفض الأول', 'تثبيت الكابتن البديل'],
    },
    {
      id: 'DA-2003',
      status: 'نقص كباتن',
      statusTone: 'danger',
      captain: 'لا يوجد',
      distance: '-',
      pickupEta: '-',
      dropoffEta: '-',
      confidence: 'ثقة منخفضة',
      blocker: 'نقص في التغطية',
      readyForPickup: 'يحتاج تصعيدًا',
      recommendation: 'صعّد وراقب الضغط',
      note: 'المنطقة تحتاج تدخلًا مباشرًا.',
      actionPlans: ['تصعيد فوري', 'تثبيت العجز', 'فتح الضغط'],
    },
  ] as const,
} as const;

export const SHEIN_PROXY_OPERATIONAL_PREVIEW = {
  summary: {
    underReview: 12,
    estimated: 8,
    offered: 6,
    scheduled: 5,
    approved: 4,
    cancelled: 1,
  },
  requests: [
    {
      id: 'SPX-2048',
      customer: 'نورة الفهد',
      statusKey: 'under-review',
      statusLabel: 'قيد المراجعة',
      statusTone: 'warning',
      amount: 'ر.س 1,280',
      shipping: 'ر.س 96',
      fee: 'ر.س 110',
      total: 'ر.س 1,486',
      updated: 'قبل 10 دقائق',
      note: 'بانتظار أول تقدير من فريق الإسناد.',
      nextStep: 'افتح التقدير',
    },
    {
      id: 'SPX-2051',
      customer: 'مريم خالد',
      statusKey: 'estimated',
      statusLabel: 'التقدير جاهز',
      statusTone: 'brand',
      amount: 'ر.س 840',
      shipping: 'ر.س 62',
      fee: 'ر.س 88',
      total: 'ر.س 990',
      updated: 'قبل 18 دقيقة',
      note: 'يمكن تحويله مباشرة إلى عرض.',
      nextStep: 'حوّل إلى العرض',
    },
    {
      id: 'SPX-2064',
      customer: 'سعيد حسن',
      statusKey: 'offered',
      statusLabel: 'العرض مرسل',
      statusTone: 'warning',
      amount: 'ر.س 1,620',
      shipping: 'ر.س 74',
      fee: 'ر.س 125',
      total: 'ر.س 1,819',
      updated: 'قبل 32 دقيقة',
      note: 'العرض خارج وينتظر رد العميل.',
      nextStep: 'تابع رد العميل',
    },
    {
      id: 'SPX-2072',
      customer: 'دانا صالح',
      statusKey: 'scheduled',
      statusLabel: 'مجدول',
      statusTone: 'best',
      amount: 'ر.س 1,010',
      shipping: 'ر.س 55',
      fee: 'ر.س 94',
      total: 'ر.س 1,159',
      updated: 'قبل ساعة',
      note: 'نافذة الاستلام مثبتة للدفعة التالية.',
      nextStep: 'ثبّت نافذة الاستلام',
    },
    {
      id: 'SPX-2078',
      customer: 'لمى ناصر',
      statusKey: 'approved',
      statusLabel: 'معتمد',
      statusTone: 'best',
      amount: 'ر.س 690',
      shipping: 'ر.س 45',
      fee: 'ر.س 77',
      total: 'ر.س 812',
      updated: 'قبل ساعتين',
      note: 'جاهز لتسليم اليدوية.',
      nextStep: 'أكمل الإسناد',
    },
    {
      id: 'SPX-2083',
      customer: 'عبدالله عمر',
      statusKey: 'cancelled',
      statusLabel: 'ملغى',
      statusTone: 'danger',
      amount: 'ر.س 560',
      shipping: 'ر.س 41',
      fee: 'ر.س 58',
      total: 'ر.س 659',
      updated: 'قبل 3 ساعات',
      note: 'أُلغي بعد تعارض في التسعير.',
      nextStep: 'أغلق السجل',
    },
  ] as const,
} as const;

export const AWNAK_OPERATIONAL_PREVIEW = {
  summary: {
    underReview: 9,
    confirmed: 4,
    inFollowUp: 6,
    escalationNeeded: 2,
  },
  rows: [
    {
      requestId: 'AWN-3101',
      type: 'طلب استلام معلق',
      customer: 'نورة الفهد',
      status: 'قيد المراجعة',
      assignmentStatus: 'معلّق',
      workflowState: 'تقدير',
      nextAction: 'راجع الآن',
      risk: 'مرتفع',
      owner: 'فريق عونك',
      note: 'الطلب يحتاج قرارًا سريعًا قبل الإرسال.',
      statusTone: 'warning',
    },
    {
      requestId: 'AWN-3104',
      type: 'طلب متابعة التوصيل',
      customer: 'مريم خالد',
      status: 'قيد العرض',
      assignmentStatus: 'قيد التثبيت',
      workflowState: 'عرض',
      nextAction: 'ثبّت الخطوة',
      risk: 'متوسط',
      owner: 'المشرف المباشر',
      note: 'القرار جاهز لكن التوقيت يحتاج تثبيت.',
      statusTone: 'brand',
    },
    {
      requestId: 'AWN-3108',
      type: 'موعد تسليم قريب',
      customer: 'سعيد حسن',
      status: 'مجدول',
      assignmentStatus: 'مثبّت',
      workflowState: 'جدولة',
      nextAction: 'أغلق بعد التحقق',
      risk: 'منخفض',
      owner: 'التشغيل',
      note: 'كل الإشارات مكتملة ويمكن الإغلاق بعد التأكيد.',
      statusTone: 'best',
    },
  ] as const,
} as const;

export const AREA_CAPACITY_OPERATIONAL_PREVIEW = {
  summary: {
    zoneLoad: 'أحمال مرتفعة',
    protectedZones: 2,
    freeZones: 1,
    surgeBonus: 'حافز المنطقة',
    recommendation: 'فعّل حافز المنطقة الآن',
  },
  zones: [
    {
      id: 'AR-01',
      zone: 'شمال الرياض',
      zoneLoad: 'مرتفع',
      protectedZones: '2',
      freeZones: '0',
      surgeBonus: 'حافز مفعل',
      reduceRadius: 'تقليل النطاق',
      temporaryStop: 'إيقاف مؤقت متاح',
      moveCapacity: 'نقل السعة',
      recommendation: 'فعّل حافز المنطقة الآن',
      note: 'العجز يحتاج تدخلًا فوريًا.',
      statusTone: 'danger',
    },
    {
      id: 'AR-02',
      zone: 'شرق الرياض',
      zoneLoad: 'متصاعد',
      protectedZones: '1',
      freeZones: '1',
      surgeBonus: 'حافز جزئي',
      reduceRadius: 'تقليل نصف القطر',
      temporaryStop: 'متاح للحظات',
      moveCapacity: 'نقل كباتن',
      recommendation: 'قلّص النطاق مؤقتًا',
      note: 'الضغط سيزيد خلال 15 دقيقة.',
      statusTone: 'warning',
    },
    {
      id: 'AR-03',
      zone: 'وسط الرياض',
      zoneLoad: 'متوازن',
      protectedZones: '3',
      freeZones: '2',
      surgeBonus: 'لا حاجة',
      reduceRadius: 'غير مطلوب',
      temporaryStop: 'غير مطلوب',
      moveCapacity: 'نقل بضع كباتن',
      recommendation: 'لا تدخل مطلوب',
      note: 'التغطية مستقرة والفائض واضح.',
      statusTone: 'best',
    },
    {
      id: 'AR-04',
      zone: 'جنوب الرياض',
      zoneLoad: 'فائض',
      protectedZones: '2',
      freeZones: '4',
      surgeBonus: 'احتياطي',
      reduceRadius: 'لا حاجة',
      temporaryStop: 'لا حاجة',
      moveCapacity: 'انقل الكباتن للشمال',
      recommendation: 'انقل السعة للمناطق المضغوطة',
      note: 'يمكن دعم الشمال مباشرة من هنا.',
      statusTone: 'brand',
    },
  ] as const,
} as const;

export const EXCEPTIONS_ESCALATIONS_OPERATIONAL_PREVIEW = {
  summary: {
    open: 17,
    escalate: 4,
    resolve: 12,
    close: 29,
  },
  exceptions: [
    {
      id: 'EX-4101',
      type: 'تأخير غير مبرر',
      severity: 'عالي',
      currentOwner: 'الإسناد',
      startTime: 'منذ 15 دقيقة',
      lastAction: 'تنبيه للكابتن',
      suggestedAction: 'إعادة الإسناد',
      resolutionPath: 'حل',
      note: 'التأخير ما زال مفتوحًا بلا مالك واضح.',
      statusTone: 'warning',
    },
    {
      id: 'EX-4102',
      type: 'تعطل مركبة كابتن',
      severity: 'حرج',
      currentOwner: 'الدعم الفني',
      startTime: 'منذ 8 دقائق',
      lastAction: 'قيد التواصل',
      suggestedAction: 'إسناد بديل',
      resolutionPath: 'تصعيد',
      note: 'الحل يحتاج تدخلًا مباشرًا وسريعًا.',
      statusTone: 'danger',
    },
    {
      id: 'EX-4103',
      type: 'إغلاق متجر مفاجئ',
      severity: 'متوسط',
      currentOwner: 'إدارة الشركاء',
      startTime: 'منذ 25 دقيقة',
      lastAction: 'إيقاف الاستقبال',
      suggestedAction: 'تثبيت الإغلاق',
      resolutionPath: 'إغلاق',
      note: 'الاستقبال متوقف ولا حاجة لتكرار الإجراء.',
      statusTone: 'best',
    },
  ] as const,
} as const;

export const AUDIT_SUPPORT_SLA_OPERATIONAL_PREVIEW = {
  summary: {
    manualAudits: 12,
    supportTickets: 6,
    slaRisk: 5,
    evidenceComplete: 84,
  },
  audits: [
    {
      id: 'AU-7001',
      who: 'المشرف',
      why: 'إسناد يدوي بعد تأخر الكابتن',
      when: 'منذ 10 دقائق',
      permissionResult: 'موافق',
      slaBreachReason: 'تأخر الاستلام',
      supportTicketLink: 'تذكرة-51',
      proofRequired: 'صورة إيصال',
      evidenceState: 'مفتوح',
      resolutionPath: 'حل',
      note: 'يحتاج إغلاقًا بعد حفظ الإثبات.',
      statusTone: 'danger',
    },
    {
      id: 'AU-7002',
      who: 'الدعم',
      why: 'شكوى عميل حي',
      when: 'منذ 22 دقيقة',
      permissionResult: 'قيد الموافقة',
      slaBreachReason: 'نقص الطلب',
      supportTicketLink: 'تذكرة-52',
      proofRequired: 'رسالة من المتجر',
      evidenceState: 'يحتاج إثبات',
      resolutionPath: 'تصعيد',
      note: 'الربط بالدعم هو الخطوة التالية.',
      statusTone: 'warning',
    },
    {
      id: 'AU-7003',
      who: 'العمليات',
      why: 'تعويض مباشر',
      when: 'منذ ساعة',
      permissionResult: 'معتمد',
      slaBreachReason: 'تأخير متجر',
      supportTicketLink: 'تذكرة-53',
      proofRequired: 'حزمة إثبات كاملة',
      evidenceState: 'مكتمل',
      resolutionPath: 'إغلاق',
      note: 'يمكن الإغلاق دون المزيد من الخطوات.',
      statusTone: 'best',
    },
  ] as const,
} as const;
