/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Service health probe
         * @description Liveness probe — returns ok when the WLT service is running and accepting requests.
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payment/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create payment session (DSH checkout handoff to WLT)
         * @description DSH calls this when the client confirms checkout. WLT creates a payment session and holds the funds.
         */
        post: operations["createPaymentSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payment/sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get payment session status
         * @description Returns the current state and metadata of a payment session by ID.
         */
        get: operations["getPaymentSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payment/sessions/{id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm payment — provider webhook or operator test-confirm
         * @description WLT confirms payment and calls DSH POST /checkout/payment-callback:
         *       X-WLT-Callback-Token, X-WLT-Event-Id, Idempotency-Key headers
         *       Body: {intent_id, wlt_payment_ref_id, status: "confirmed"}
         */
        post: operations["confirmPaymentSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payment/sessions/{id}/fail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Fail payment — provider webhook or operator
         * @description Transitions payment session to FAILED state and notifies DSH via payment callback.
         */
        post: operations["failPaymentSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/refunds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Initiate refund (operator — WLT financial decision)
         * @description Creates a refund record in PENDING state. WLT is the sole owner of refund authorization and execution.
         */
        post: operations["createRefund"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/refunds/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get refund status
         * @description Returns the current state of a refund by ID.
         */
        get: operations["getRefund"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/refunds/{id}/process": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Operator approves refund (PENDING → PROCESSING)
         * @description Operator moves a pending refund to PROCESSING state, authorizing the fund release.
         */
        post: operations["processRefund"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/refunds/{id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm refund (PROCESSING → CONFIRMED) + notify DSH
         * @description WLT confirms refund and calls DSH POST /orders/{order_id}/refund-callback:
         *       X-WLT-Callback-Token header
         *       Body: {refund_ref_id: refund.id, status: "CONFIRMED"}
         */
        post: operations["confirmRefund"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/refunds/{id}/fail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Fail refund + notify DSH
         * @description Transitions refund to FAILED state and dispatches a failure callback to DSH.
         */
        post: operations["failRefund"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settlements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List settlements (operator)
         * @description Returns a paginated list of settlement records, optionally filtered by status.
         */
        get: operations["listSettlements"];
        put?: never;
        /**
         * Create settlement for a delivered order (operator)
         * @description Creates a settlement record for a delivered order. WLT calculates platform/captain fees and creates the payout record.
         */
        post: operations["createSettlement"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settlements/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get settlement detail
         * @description Returns the full detail of a single settlement record including fee breakdown.
         */
        get: operations["getSettlement"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settlements/{id}/process": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Move settlement PENDING → PROCESSING
         * @description Operator initiates payout processing for a pending settlement.
         */
        post: operations["processSettlement"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settlements/{id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Complete settlement PROCESSING → COMPLETED
         * @description Marks the settlement as fully disbursed. Triggers payout record finalization.
         */
        post: operations["completeSettlement"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settlements/{id}/fail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Fail settlement
         * @description Marks the settlement as failed. Records the reason and unlocks retry eligibility.
         */
        post: operations["failSettlement"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wallets/{subject}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Wallet balance and aggregate stats for a subject
         * @description Operators can query any subject.
         *     Clients/captains/partners can only query their own subject.
         */
        get: operations["getWalletSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wallets/{subject}/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Paginated ledger entries for a subject
         * @description Returns paginated wallet transaction history (debits/credits) for a given subject (client, partner, captain).
         */
        get: operations["getWalletTransactions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            /** @example invalid_parameter */
            error: string;
            message?: string;
        };
        PaymentSession: {
            /** @description WLT payment session ID — stored as wlt_payment_ref_id in DSH */
            id: string;
            checkout_intent_id: string;
            client_id: string;
            /** Format: double */
            amount: number;
            /** @example YER */
            currency: string;
            /** @enum {string} */
            status: "PENDING" | "CONFIRMED" | "FAILED" | "EXPIRED" | "CANCELLED";
            /** @example wallet */
            payment_method: string;
            provider_ref?: string | null;
            failure_reason?: ("insufficient_balance" | "policy_block" | "fraud_hold" | "expired" | "provider_error") | null;
            idempotency_key: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            expires_at: string;
            /** Format: date-time */
            confirmed_at?: string | null;
            /** Format: date-time */
            failed_at?: string | null;
        };
        Refund: {
            /** @description WLT refund ID — stored as wlt_refund_ref_id in DSH */
            id: string;
            order_id: string;
            payment_session_id?: string;
            client_id: string;
            /** Format: double */
            amount: number;
            /** @example YER */
            currency: string;
            reason: string;
            /** @enum {string} */
            status: "PENDING" | "PROCESSING" | "CONFIRMED" | "FAILED";
            /** @description WltRefundTriggerRef from DSH delivery-failure event */
            trigger_ref?: string | null;
            failure_reason?: string | null;
            /** Format: date-time */
            dsh_callback_sent_at?: string | null;
            idempotency_key: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            /** Format: date-time */
            completed_at?: string | null;
        };
        Settlement: {
            /** @description WLT settlement ID — stored as wlt_settlement_ref_id in DSH */
            id: string;
            order_id: string;
            partner_id: string;
            captain_id?: string | null;
            /** Format: double */
            gross_amount: number;
            /** Format: double */
            platform_fee: number;
            /** Format: double */
            partner_payout: number;
            /** Format: double */
            captain_payout: number;
            /** @example YER */
            currency: string;
            /** @enum {string} */
            status: "PENDING" | "PROCESSING" | "COMPLETED" | "FAILED";
            failure_reason?: string | null;
            idempotency_key: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            /** Format: date-time */
            completed_at?: string | null;
        };
        WalletSummary: {
            subject: string;
            /** @enum {string} */
            actor_type: "client" | "captain" | "partner" | "field" | "operator";
            /** Format: double */
            balance: number;
            /** @example YER */
            currency: string;
            /** Format: double */
            total_credit: number;
            /** Format: double */
            total_debit: number;
            /** Format: double */
            pending_credit: number;
            /** Format: double */
            pending_debit: number;
            transaction_count: number;
        };
        LedgerEntry: {
            id: string;
            wallet_id: string;
            subject: string;
            /** @enum {string} */
            transaction_type: "CREDIT" | "DEBIT";
            /** Format: double */
            amount: number;
            currency: string;
            /** @enum {string} */
            reference_type: "payment_session" | "refund" | "settlement";
            reference_id: string;
            order_id?: string | null;
            description: string;
            /** @enum {string} */
            status: "PENDING" | "COMPLETED" | "FAILED" | "REVERSED";
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            completed_at?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ok */
                        status?: string;
                        /** @example wlt-api */
                        service?: string;
                    };
                };
            };
        };
    };
    createPaymentSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    checkout_intent_id: string;
                    client_id: string;
                    /** Format: double */
                    amount: number;
                    /** @default YER */
                    currency?: string;
                    /** @default wallet */
                    payment_method?: string;
                    /** @description DSH base URL for callback; uses WLT_DSH_BASE_URL env if omitted */
                    dsh_base_url?: string;
                    idempotency_key: string;
                };
            };
        };
        responses: {
            /** @description Payment session created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentSession"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getPaymentSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Payment session */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentSession"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    confirmPaymentSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    provider_ref?: string;
                };
            };
        };
        responses: {
            /** @description Confirmed; DSH payment callback dispatched */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentSession"];
                };
            };
            /** @description Forbidden — operator or system role required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Session not in PENDING state */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    failPaymentSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    failure_reason?: "insufficient_balance" | "policy_block" | "fraud_hold" | "expired" | "provider_error";
                };
            };
        };
        responses: {
            /** @description Failed; DSH payment callback dispatched */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentSession"];
                };
            };
        };
    };
    createRefund: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    order_id: string;
                    payment_session_id?: string;
                    client_id: string;
                    /** Format: double */
                    amount: number;
                    /** @default YER */
                    currency?: string;
                    reason?: string;
                    /** @description WltRefundTriggerRef bridged from DSH delivery-failure */
                    trigger_ref?: string | null;
                    dsh_base_url?: string;
                    idempotency_key: string;
                };
            };
        };
        responses: {
            /** @description Refund created in PENDING state */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refund"];
                };
            };
        };
    };
    getRefund: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Refund */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refund"];
                };
            };
        };
    };
    processRefund: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Refund now PROCESSING */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refund"];
                };
            };
        };
    };
    confirmRefund: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Refund confirmed; DSH callback dispatched */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refund"];
                };
            };
        };
    };
    failRefund: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    reason?: string;
                };
            };
        };
        responses: {
            /** @description Refund failed; DSH callback dispatched */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refund"];
                };
            };
        };
    };
    listSettlements: {
        parameters: {
            query?: {
                status?: "PENDING" | "PROCESSING" | "COMPLETED" | "FAILED";
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Settlements list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        settlements?: components["schemas"]["Settlement"][];
                        total?: number;
                    };
                };
            };
        };
    };
    createSettlement: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    order_id: string;
                    partner_id: string;
                    captain_id?: string | null;
                    /** Format: double */
                    gross_amount: number;
                    /**
                     * Format: double
                     * @default 0.1
                     */
                    platform_fee_rate?: number;
                    /**
                     * Format: double
                     * @default 0.15
                     */
                    captain_fee_rate?: number;
                    /** @default YER */
                    currency?: string;
                    idempotency_key: string;
                };
            };
        };
        responses: {
            /** @description Settlement created in PENDING state */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settlement"];
                };
            };
        };
    };
    getSettlement: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Settlement */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settlement"];
                };
            };
        };
    };
    processSettlement: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Settlement now PROCESSING */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settlement"];
                };
            };
        };
    };
    completeSettlement: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Settlement completed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settlement"];
                };
            };
        };
    };
    failSettlement: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    reason?: string;
                };
            };
        };
        responses: {
            /** @description Settlement failed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settlement"];
                };
            };
        };
    };
    getWalletSummary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                subject: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Wallet summary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WalletSummary"];
                };
            };
            /** @description Cannot view another subject's wallet */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getWalletTransactions: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                subject: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ledger entries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        entries?: components["schemas"]["LedgerEntry"][];
                        total?: number;
                    };
                };
            };
        };
    };
}
