import type { DshClientRouteId } from './dsh-client.routes';

export type DshClientScreenRegistryItem = {
  readonly screenId: string;
  readonly routeId: DshClientRouteId;
  readonly surfaceId: 'app-client';
  readonly ownerKind: 'app' | 'service' | 'integration';
  readonly ownerId: 'app-client' | 'dsh' | 'wlt.dsh';
  readonly serviceId?: 'dsh' | 'wlt';
  readonly linkedServiceId?: 'dsh' | 'wlt';
  readonly ownerPath: string;
  readonly componentName: string;
  readonly screenKind: 'TAB_ROOT' | 'SCREEN_ENTRY' | 'FLOW_STEP' | 'MODAL' | 'SHEET';
  readonly flowId?: string;
  readonly requiredPermissions?: readonly ('location' | 'notifications' | 'camera' | 'mediaLibrary')[];
  readonly analytics: {
    readonly screenView: string;
  };
  readonly deepLinkPath?: string;
  readonly fallbackRouteId?: DshClientRouteId;
  readonly releaseCriticality: 'P0' | 'P1' | 'P2';
  readonly requiredStates: readonly DshClientScreenState[];
  readonly status: DshClientScreenRegistryStatus;
};

export type DshClientScreenState =
  | 'loading'
  | 'empty'
  | 'error'
  | 'success'
  | 'offline'
  | 'disabled'
  | 'retry'
  | 'blocked'
  | 'cancelled';

export type DshClientScreenRegistryStatus =
  | 'READY_FOR_REVIEW'
  | 'VERIFIED'
  | 'DEPRECATED';

export const dshClientScreenRegistry = [
  {
    screenId: 'client.dsh.home.feed',
    routeId: 'dsh-home',
    surfaceId: 'app-client',
    ownerKind: 'service',
    ownerId: 'dsh',
    serviceId: 'dsh',
    ownerPath: 'dsh/frontend/app-client/screens/HomeScreen.tsx',
    componentName: 'DshHomeGetScreen',
    screenKind: 'TAB_ROOT',
    flowId: 'dsh.discovery',
    requiredStates: ['loading', 'empty', 'error', 'success', 'offline'],
    analytics: { screenView: 'client_dsh_home_feed_view' },
    deepLinkPath: '/dsh',
    fallbackRouteId: 'dsh-home',
    releaseCriticality: 'P0',
    status: 'VERIFIED',
  },
  {
    screenId: 'client.dsh.entry',
    routeId: 'dsh-entry',
    surfaceId: 'app-client',
    ownerKind: 'service',
    ownerId: 'dsh',
    serviceId: 'dsh',
    ownerPath: 'dsh/frontend/app-client/screens/EntryScreen.tsx',
    componentName: 'DshEntryScreen',
    screenKind: 'SCREEN_ENTRY',
    flowId: 'dsh.entry',
    requiredStates: ['loading', 'empty', 'error', 'success', 'offline'],
    analytics: { screenView: 'client_dsh_entry_view' },
    fallbackRouteId: 'dsh-home',
    releaseCriticality: 'P1',
    status: 'VERIFIED',
  },
  {
    screenId: 'client.dsh.my-space.home',
    routeId: 'dsh-my-space',
    surfaceId: 'app-client',
    ownerKind: 'service',
    ownerId: 'dsh',
    serviceId: 'dsh',
    ownerPath: 'dsh/frontend/app-client/screens/MySpaceScreen.tsx',
    componentName: 'DshMySpaceScreen',
    screenKind: 'SCREEN_ENTRY',
    flowId: 'dsh.my-space',
    requiredStates: ['loading', 'empty', 'error', 'success', 'offline', 'disabled'],
    analytics: { screenView: 'client_dsh_my_space_view' },
    fallbackRouteId: 'dsh-home',
    releaseCriticality: 'P1',
    status: 'VERIFIED',
  },
  {
    screenId: 'client.dsh.notifications.list',
    routeId: 'dsh-notifications',
    surfaceId: 'app-client',
    ownerKind: 'service',
    ownerId: 'dsh',
    serviceId: 'dsh',
    ownerPath: 'dsh/frontend/app-client/screens/NotificationsScreen.tsx',
    componentName: 'DshNotificationsScreen',
    screenKind: 'SCREEN_ENTRY',
    flowId: 'dsh.notifications',
    requiredStates: ['loading', 'empty', 'error', 'success', 'offline', 'disabled'],
    requiredPermissions: ['notifications'],
    analytics: { screenView: 'client_dsh_notifications_list_view' },
    fallbackRouteId: 'dsh-home',
    releaseCriticality: 'P1',
    status: 'VERIFIED',
  },
  {
    screenId: 'client.dsh.store.items',
    routeId: 'dsh-store-items',
    surfaceId: 'app-client',
    ownerKind: 'service',
    ownerId: 'dsh',
    serviceId: 'dsh',
    ownerPath: 'dsh/frontend/app-client/screens/StoreItemsScreen.tsx',
    componentName: 'DshStoreItemsScreen',
    screenKind: 'FLOW_STEP',
    flowId: 'dsh.storefront',
    requiredStates: ['loading', 'empty', 'error', 'success', 'offline'],
    analytics: { screenView: 'client_dsh_store_items_view' },
    fallbackRouteId: 'dsh-store',
    releaseCriticality: 'P1',
    status: 'VERIFIED',
  },
  {
    screenId: 'client.dsh.cart.review',
    routeId: 'dsh-cart',
    surfaceId: 'app-client',
    ownerKind: 'service',
    ownerId: 'dsh',
    serviceId: 'dsh',
    linkedServiceId: 'wlt',
    ownerPath: 'dsh/frontend/app-client/screens/CartScreen.tsx',
    componentName: 'DshCartGetScreen',
    screenKind: 'FLOW_STEP',
    flowId: 'dsh.checkout',
    requiredStates: ['loading', 'empty', 'error', 'success', 'offline', 'blocked', 'retry'],
    analytics: { screenView: 'client_dsh_cart_review_view' },
    fallbackRouteId: 'dsh-store',
    releaseCriticality: 'P0',
    status: 'VERIFIED',
  },
  {
    screenId: 'client.dsh.store.details',
    routeId: 'dsh-store',
    surfaceId: 'app-client',
    ownerKind: 'service',
    ownerId: 'dsh',
    serviceId: 'dsh',
    ownerPath: 'dsh/frontend/app-client/screens/StoreScreen.tsx',
    componentName: 'DshStoreGetScreen',
    screenKind: 'FLOW_STEP',
    flowId: 'dsh.storefront',
    requiredStates: ['loading', 'empty', 'error', 'success', 'offline'],
    analytics: { screenView: 'client_dsh_store_details_view' },
    fallbackRouteId: 'dsh-home',
    releaseCriticality: 'P0',
    status: 'VERIFIED',
  },
  {
    screenId: 'client.dsh.bell',
    routeId: 'dsh-bell',
    surfaceId: 'app-client',
    ownerKind: 'service',
    ownerId: 'dsh',
    serviceId: 'dsh',
    ownerPath: 'dsh/frontend/app-client/screens/BellScreen.tsx',
    componentName: 'DshClientBellScreen',
    screenKind: 'MODAL',
    flowId: 'dsh.notifications',
    requiredStates: ['loading', 'empty', 'error', 'success', 'offline'],
    analytics: { screenView: 'client_dsh_bell_view' },
    fallbackRouteId: 'dsh-tracking',
    releaseCriticality: 'P2',
    status: 'VERIFIED',
  },
  {
    screenId: 'client.dsh.benefits.home',
    routeId: 'dsh-benefits',
    surfaceId: 'app-client',
    ownerKind: 'service',
    ownerId: 'dsh',
    serviceId: 'dsh',
    ownerPath: 'dsh/frontend/app-client/screens/BenefitsScreen.tsx',
    componentName: 'DshBenefitsHubScreen',
    screenKind: 'FLOW_STEP',
    flowId: 'dsh.benefits',
    requiredStates: ['loading', 'empty', 'error', 'success', 'offline', 'blocked'],
    analytics: { screenView: 'client_dsh_benefits_home_view' },
    fallbackRouteId: 'dsh-home',
    releaseCriticality: 'P1',
    status: 'VERIFIED',
  },
  {
    screenId: 'client.dsh.conversation.workspace',
    routeId: 'dsh-conversation-workspace',
    surfaceId: 'app-client',
    ownerKind: 'service',
    ownerId: 'dsh',
    serviceId: 'dsh',
    ownerPath: 'dsh/frontend/app-client/screens/DshConversationHubScreen.tsx',
    componentName: 'DshConversationHubScreen',
    screenKind: 'FLOW_STEP',
    flowId: 'dsh.support.chat',
    requiredStates: ['loading', 'error', 'success', 'retry', 'blocked'],
    analytics: { screenView: 'client_dsh_conversation_workspace_view' },
    fallbackRouteId: 'dsh-orders',
    releaseCriticality: 'P1',
    status: 'VERIFIED',
  },
  {
    screenId: 'client.dsh.listing.status-update',
    routeId: 'dsh-listing-status-update',
    surfaceId: 'app-client',
    ownerKind: 'service',
    ownerId: 'dsh',
    serviceId: 'dsh',
    ownerPath: 'dsh/frontend/app-client/screens/DshListingStatusUpdateScreen.tsx',
    componentName: 'DshListingStatusUpdateScreen',
    screenKind: 'FLOW_STEP',
    flowId: 'dsh.operations.listing',
    requiredStates: ['loading', 'error', 'success', 'retry', 'blocked'],
    analytics: { screenView: 'client_dsh_listing_status_update_view' },
    fallbackRouteId: 'dsh-home',
    releaseCriticality: 'P2',
    status: 'VERIFIED',
  },
  {
    screenId: 'client.dsh.order.issue.workspace',
    routeId: 'dsh-order-issue-workspace',
    surfaceId: 'app-client',
    ownerKind: 'service',
    ownerId: 'dsh',
    serviceId: 'dsh',
    ownerPath: 'dsh/frontend/app-client/screens/DshOrderIssueHubScreen.tsx',
    componentName: 'DshOrderIssueHubScreen',
    screenKind: 'FLOW_STEP',
    flowId: 'dsh.support.issue',
    requiredStates: ['loading', 'error', 'success', 'retry', 'blocked'],
    analytics: { screenView: 'client_dsh_order_issue_workspace_view' },
    fallbackRouteId: 'dsh-orders',
    releaseCriticality: 'P1',
    status: 'VERIFIED',
  },
  {
    screenId: 'client.dsh.proxy.workspace',
    routeId: 'dsh-proxy-workspace',
    surfaceId: 'app-client',
    ownerKind: 'service',
    ownerId: 'dsh',
    serviceId: 'dsh',
    ownerPath: 'dsh/frontend/app-client/screens/DshProxyHubScreen.tsx',
    componentName: 'DshProxyHubScreen',
    screenKind: 'FLOW_STEP',
    flowId: 'dsh.proxy',
    requiredStates: ['loading', 'error', 'success', 'retry', 'blocked'],
    analytics: { screenView: 'client_dsh_proxy_workspace_view' },
    fallbackRouteId: 'dsh-orders',
    releaseCriticality: 'P2',
    status: 'VERIFIED',
  },
  {
    screenId: 'client.dsh.service.settings',
    routeId: 'dsh-service-settings',
    surfaceId: 'app-client',
    ownerKind: 'service',
    ownerId: 'dsh',
    serviceId: 'dsh',
    ownerPath: 'dsh/frontend/app-client/screens/DshServiceSettingsHubScreen.tsx',
    componentName: 'DshServiceSettingsHubScreen',
    screenKind: 'FLOW_STEP',
    flowId: 'dsh.service-settings',
    requiredStates: ['loading', 'error', 'success', 'retry', 'blocked'],
    analytics: { screenView: 'client_dsh_service_settings_view' },
    fallbackRouteId: 'dsh-home',
    releaseCriticality: 'P2',
    status: 'VERIFIED',
  },
  {
    screenId: 'client.dsh.zone.set',
    routeId: 'dsh-zone-set',
    surfaceId: 'app-client',
    ownerKind: 'service',
    ownerId: 'dsh',
    serviceId: 'dsh',
    ownerPath: 'dsh/frontend/app-client/screens/DshZoneSetScreen.tsx',
    componentName: 'DshZoneSetScreen',
    screenKind: 'FLOW_STEP',
    flowId: 'dsh.service-zone',
    requiredStates: ['loading', 'error', 'success', 'retry', 'blocked'],
    analytics: { screenView: 'client_dsh_zone_set_view' },
    fallbackRouteId: 'dsh-home',
    releaseCriticality: 'P2',
    status: 'VERIFIED',
  },
  {
    screenId: 'client.dsh.orders.history',
    routeId: 'dsh-orders',
    surfaceId: 'app-client',
    ownerKind: 'service',
    ownerId: 'dsh',
    serviceId: 'dsh',
    ownerPath: 'dsh/frontend/app-client/screens/DshOrdersListScreen.tsx',
    componentName: 'DshOrdersListScreen',
    screenKind: 'SCREEN_ENTRY',
    flowId: 'dsh.orders',
    requiredStates: ['loading', 'empty', 'error', 'success', 'offline'],
    analytics: { screenView: 'client_dsh_orders_history_view' },
    deepLinkPath: '/dsh/orders',
    fallbackRouteId: 'dsh-home',
    releaseCriticality: 'P0',
    status: 'VERIFIED',
  },
  {
    screenId: 'client.dsh.order.smart-followup',
    routeId: 'dsh-tracking',
    surfaceId: 'app-client',
    ownerKind: 'service',
    ownerId: 'dsh',
    serviceId: 'dsh',
    ownerPath: 'dsh/frontend/app-client/screens/DshTrackingScreen.tsx',
    componentName: 'DshTrackingScreen',
    screenKind: 'FLOW_STEP',
    flowId: 'dsh.tracking',
    requiredStates: ['loading', 'error', 'success', 'offline', 'retry', 'blocked'],
    analytics: { screenView: 'client_dsh_order_smart_followup_view' },
    deepLinkPath: '/dsh/orders/:orderId/tracking',
    fallbackRouteId: 'dsh-orders',
    releaseCriticality: 'P0',
    status: 'VERIFIED',
  },
  {
    screenId: 'client.dsh.checkout.intent',
    routeId: 'dsh-checkout-intent',
    surfaceId: 'app-client',
    ownerKind: 'service',
    ownerId: 'dsh',
    serviceId: 'dsh',
    ownerPath: 'dsh/frontend/app-client/screens/DshCheckoutIntentScreen.tsx',
    componentName: 'DshCheckoutIntentScreen',
    screenKind: 'FLOW_STEP',
    flowId: 'dsh.checkout',
    requiredStates: ['loading', 'error', 'blocked', 'retry'],
    analytics: { screenView: 'client_dsh_checkout_intent_view' },
    fallbackRouteId: 'dsh-cart',
    releaseCriticality: 'P0',
    status: 'READY_FOR_REVIEW',
  },
  {
    screenId: 'client.dsh.checkout.failure',
    routeId: 'dsh-checkout-failure',
    surfaceId: 'app-client',
    ownerKind: 'service',
    ownerId: 'dsh',
    serviceId: 'dsh',
    linkedServiceId: 'wlt',
    ownerPath: 'dsh/frontend/app-client/screens/DshCheckoutFailureScreen.tsx',
    componentName: 'DshCheckoutFailureScreen',
    screenKind: 'FLOW_STEP',
    flowId: 'dsh.checkout',
    requiredStates: ['loading', 'error', 'retry', 'cancelled'],
    analytics: { screenView: 'client_dsh_checkout_failure_view' },
    fallbackRouteId: 'dsh-cart',
    releaseCriticality: 'P0',
    status: 'READY_FOR_REVIEW',
  },
  {
    screenId: 'client.dsh.addresses-location.hub',
    routeId: 'dsh-addresses-location',
    surfaceId: 'app-client',
    ownerKind: 'service',
    ownerId: 'dsh',
    serviceId: 'dsh',
    ownerPath: 'dsh/frontend/app-client/screens/AddressLocationScreen.tsx',
    componentName: 'DshAddressLocationScreen',
    screenKind: 'SCREEN_ENTRY',
    flowId: 'dsh.addresses-location',
    requiredStates: ['loading', 'empty', 'error', 'success', 'offline', 'disabled'],
    analytics: { screenView: 'client_dsh_addresses_location_hub_view' },
    fallbackRouteId: 'dsh-my-space',
    releaseCriticality: 'P1',
    status: 'VERIFIED',
  },
  {
    screenId: 'client.dsh.identity.hub',
    routeId: 'dsh-identity',
    surfaceId: 'app-client',
    ownerKind: 'service',
    ownerId: 'dsh',
    serviceId: 'dsh',
    ownerPath: 'dsh/frontend/app-client/screens/DshIdentityHubScreen.tsx',
    componentName: 'DshIdentityHubScreen',
    screenKind: 'SCREEN_ENTRY',
    flowId: 'dsh.identity',
    requiredStates: ['loading', 'empty', 'error', 'success', 'offline', 'disabled'],
    analytics: { screenView: 'client_dsh_identity_hub_view' },
    fallbackRouteId: 'dsh-my-space',
    releaseCriticality: 'P1',
    status: 'VERIFIED',
  },
  {
    screenId: 'client.dsh.appearance.hub',
    routeId: 'dsh-appearance',
    surfaceId: 'app-client',
    ownerKind: 'service',
    ownerId: 'dsh',
    serviceId: 'dsh',
    ownerPath: 'dsh/frontend/app-client/screens/DshAppearanceHubScreen.tsx',
    componentName: 'DshAppearanceHubScreen',
    screenKind: 'SCREEN_ENTRY',
    flowId: 'dsh.appearance',
    requiredStates: ['loading', 'empty', 'error', 'success', 'offline', 'disabled'],
    analytics: { screenView: 'client_dsh_appearance_hub_view' },
    fallbackRouteId: 'dsh-my-space',
    releaseCriticality: 'P1',
    status: 'VERIFIED',
  },
  {
    screenId: 'client.dsh.preferences.hub',
    routeId: 'dsh-preferences',
    surfaceId: 'app-client',
    ownerKind: 'service',
    ownerId: 'dsh',
    serviceId: 'dsh',
    ownerPath: 'dsh/frontend/app-client/screens/DshPreferencesHubScreen.tsx',
    componentName: 'DshPreferencesHubScreen',
    screenKind: 'SCREEN_ENTRY',
    flowId: 'dsh.preferences',
    requiredStates: ['loading', 'empty', 'error', 'success', 'offline', 'disabled'],
    analytics: { screenView: 'client_dsh_preferences_hub_view' },
    fallbackRouteId: 'dsh-my-space',
    releaseCriticality: 'P1',
    status: 'VERIFIED',
  },
] as const satisfies readonly DshClientScreenRegistryItem[];
