import type { DshClientRouteId } from './dsh-client.routes';

export type DshClientScreenRegistryItem = {
  readonly screenId: string;
  readonly routeId: DshClientRouteId;
  readonly surfaceId: 'app-client';
  readonly ownerKind: 'app' | 'service' | 'integration';
  readonly ownerId: 'app-client' | 'dsh' | 'wlt.dsh';
  readonly serviceId?: 'dsh' | 'wlt';
  readonly linkedServiceId?: 'dsh' | 'wlt';
  readonly ownerPath: string;
  readonly componentName: string;
  readonly screenKind: 'TAB_ROOT' | 'SCREEN_ENTRY' | 'FLOW_STEP' | 'MODAL' | 'SHEET';
  readonly flowId?: string;
  readonly requiredStates: readonly ('loading' | 'empty' | 'error' | 'success' | 'offline' | 'disabled' | 'retry' | 'blocked')[];
  readonly requiredPermissions?: readonly ('location' | 'notifications' | 'camera' | 'mediaLibrary')[];
  readonly analytics: {
    readonly screenView: string;
  };
  readonly deepLinkPath?: string;
  readonly fallbackRouteId?: DshClientRouteId;
  readonly releaseCriticality: 'P0' | 'P1' | 'P2';
  readonly status: 'TBD' | 'UNPROVEN' | 'VERIFIED' | 'CLOSED' | 'DEPRECATED';
};

export const dshClientScreenRegistry = [
  {
    screenId: 'client.dsh.home.feed',
    routeId: 'dsh-home',
    surfaceId: 'app-client',
    ownerKind: 'service',
    ownerId: 'dsh',
    serviceId: 'dsh',
    ownerPath: 'dsh/frontend/app-client/screens/HomeScreen.tsx',
    componentName: 'DshHomeGetScreen',
    screenKind: 'TAB_ROOT',
    flowId: 'dsh.discovery',
    requiredStates: ['loading', 'empty', 'error', 'success', 'offline'],
    analytics: { screenView: 'client_dsh_home_feed_view' },
    deepLinkPath: '/dsh',
    fallbackRouteId: 'dsh-home',
    releaseCriticality: 'P0',
    status: 'VERIFIED',
  },
  {
    screenId: 'client.dsh.entry',
    routeId: 'dsh-entry',
    surfaceId: 'app-client',
    ownerKind: 'service',
    ownerId: 'dsh',
    serviceId: 'dsh',
    ownerPath: 'dsh/frontend/app-client/screens/EntryScreen.tsx',
    componentName: 'DshEntryScreen',
    screenKind: 'SCREEN_ENTRY',
    flowId: 'dsh.entry',
    requiredStates: ['loading', 'empty', 'error', 'success', 'offline'],
    analytics: { screenView: 'client_dsh_entry_view' },
    fallbackRouteId: 'dsh-home',
    releaseCriticality: 'P1',
    status: 'VERIFIED',
  },
  {
    screenId: 'client.dsh.my-space.home',
    routeId: 'dsh-my-space',
    surfaceId: 'app-client',
    ownerKind: 'service',
    ownerId: 'dsh',
    serviceId: 'dsh',
    ownerPath: 'dsh/frontend/app-client/screens/MySpaceScreen.tsx',
    componentName: 'DshMySpaceScreen',
    screenKind: 'SCREEN_ENTRY',
    flowId: 'dsh.my-space',
    requiredStates: ['loading', 'empty', 'error', 'success', 'offline', 'disabled'],
    analytics: { screenView: 'client_dsh_my_space_view' },
    fallbackRouteId: 'dsh-home',
    releaseCriticality: 'P1',
    status: 'VERIFIED',
  },
  {
    screenId: 'client.dsh.notifications.list',
    routeId: 'dsh-notifications',
    surfaceId: 'app-client',
    ownerKind: 'service',
    ownerId: 'dsh',
    serviceId: 'dsh',
    ownerPath: 'dsh/frontend/app-client/screens/NotificationsScreen.tsx',
    componentName: 'DshNotificationsScreen',
    screenKind: 'SCREEN_ENTRY',
    flowId: 'dsh.notifications',
    requiredStates: ['loading', 'empty', 'error', 'success', 'offline', 'disabled'],
    requiredPermissions: ['notifications'],
    analytics: { screenView: 'client_dsh_notifications_list_view' },
    fallbackRouteId: 'dsh-home',
    releaseCriticality: 'P1',
    status: 'VERIFIED',
  },
  {
    screenId: 'client.dsh.store.items',
    routeId: 'dsh-store-items',
    surfaceId: 'app-client',
    ownerKind: 'service',
    ownerId: 'dsh',
    serviceId: 'dsh',
    ownerPath: 'dsh/frontend/app-client/screens/StoreItemsScreen.tsx',
    componentName: 'DshStoreItemsScreen',
    screenKind: 'FLOW_STEP',
    flowId: 'dsh.storefront',
    requiredStates: ['loading', 'empty', 'error', 'success', 'offline'],
    analytics: { screenView: 'client_dsh_store_items_view' },
    fallbackRouteId: 'dsh-store',
    releaseCriticality: 'P1',
    status: 'VERIFIED',
  },
  {
    screenId: 'client.dsh.cart.review',
    routeId: 'dsh-cart',
    surfaceId: 'app-client',
    ownerKind: 'service',
    ownerId: 'dsh',
    serviceId: 'dsh',
    linkedServiceId: 'wlt',
    ownerPath: 'dsh/frontend/app-client/screens/CartScreen.tsx',
    componentName: 'DshCartGetScreen',
    screenKind: 'FLOW_STEP',
    flowId: 'dsh.checkout',
    requiredStates: ['loading', 'empty', 'error', 'success', 'offline', 'blocked'],
    analytics: { screenView: 'client_dsh_cart_review_view' },
    fallbackRouteId: 'dsh-store',
    releaseCriticality: 'P0',
    status: 'VERIFIED',
  },
  {
    screenId: 'client.dsh.favorites.toggle',
    routeId: 'dsh-favorite-toggle',
    surfaceId: 'app-client',
    ownerKind: 'service',
    ownerId: 'dsh',
    serviceId: 'dsh',
    ownerPath: 'dsh/frontend/app-client/screens/FavoriteToggleScreen.tsx',
    componentName: 'DshFavoriteToggleScreen',
    screenKind: 'FLOW_STEP',
    flowId: 'dsh.favorites',
    requiredStates: ['loading', 'error', 'success', 'retry'],
    analytics: { screenView: 'client_dsh_favorite_toggle_view' },
    fallbackRouteId: 'dsh-favorites',
    releaseCriticality: 'P2',
    status: 'VERIFIED',
  },
  {
    screenId: 'client.dsh.favorites.list',
    routeId: 'dsh-favorites',
    surfaceId: 'app-client',
    ownerKind: 'service',
    ownerId: 'dsh',
    serviceId: 'dsh',
    ownerPath: 'dsh/frontend/app-client/screens/FavoritesScreen.tsx',
    componentName: 'DshFavoritesListScreen',
    screenKind: 'SCREEN_ENTRY',
    flowId: 'dsh.favorites',
    requiredStates: ['loading', 'empty', 'error', 'success'],
    analytics: { screenView: 'client_dsh_favorites_list_view' },
    fallbackRouteId: 'dsh-home',
    releaseCriticality: 'P2',
    status: 'VERIFIED',
  },
  {
    screenId: 'client.dsh.discovery.search',
    routeId: 'dsh-search',
    surfaceId: 'app-client',
    ownerKind: 'service',
    ownerId: 'dsh',
    serviceId: 'dsh',
    ownerPath: 'dsh/frontend/app-client/screens/SearchScreen.tsx',
    componentName: 'DshSearchScreen',
    screenKind: 'SCREEN_ENTRY',
    flowId: 'dsh.discovery',
    requiredStates: ['loading', 'empty', 'error', 'success'],
    analytics: { screenView: 'client_dsh_discovery_search_view' },
    fallbackRouteId: 'dsh-home',
    releaseCriticality: 'P1',
    status: 'VERIFIED',
  },
  {
    screenId: 'client.dsh.store.details',
    routeId: 'dsh-store',
    surfaceId: 'app-client',
    ownerKind: 'service',
    ownerId: 'dsh',
    serviceId: 'dsh',
    ownerPath: 'dsh/frontend/app-client/screens/StoreScreen.tsx',
    componentName: 'DshStoreGetScreen',
    screenKind: 'FLOW_STEP',
    flowId: 'dsh.storefront',
    requiredStates: ['loading', 'empty', 'error', 'success', 'offline'],
    analytics: { screenView: 'client_dsh_store_details_view' },
    fallbackRouteId: 'dsh-home',
    releaseCriticality: 'P0',
    status: 'VERIFIED',
  },
  {
    screenId: 'client.dsh.bell',
    routeId: 'dsh-bell',
    surfaceId: 'app-client',
    ownerKind: 'service',
    ownerId: 'dsh',
    serviceId: 'dsh',
    ownerPath: 'dsh/frontend/app-client/screens/BellScreen.tsx',
    componentName: 'DshClientBellScreen',
    screenKind: 'MODAL',
    flowId: 'dsh.notifications',
    requiredStates: ['loading', 'empty', 'error', 'success', 'offline'],
    analytics: { screenView: 'client_dsh_bell_view' },
    fallbackRouteId: 'dsh-tracking',
    releaseCriticality: 'P2',
    status: 'VERIFIED',
  },
  {
    screenId: 'client.dsh.benefits.home',
    routeId: 'dsh-benefits',
    surfaceId: 'app-client',
    ownerKind: 'service',
    ownerId: 'dsh',
    serviceId: 'dsh',
    ownerPath: 'dsh/frontend/app-client/screens/BenefitsScreen.tsx',
    componentName: 'DshBenefitsHubScreen',
    screenKind: 'FLOW_STEP',
    flowId: 'dsh.benefits',
    requiredStates: ['loading', 'empty', 'error', 'success', 'offline', 'blocked'],
    analytics: { screenView: 'client_dsh_benefits_home_view' },
    fallbackRouteId: 'dsh-home',
    releaseCriticality: 'P1',
    status: 'VERIFIED',
  },
  {
    screenId: 'client.dsh.conversation.workspace',
    routeId: 'dsh-conversation-workspace',
    surfaceId: 'app-client',
    ownerKind: 'service',
    ownerId: 'dsh',
    serviceId: 'dsh',
    ownerPath: 'dsh/frontend/app-client/screens/OperationScreens.tsx',
    componentName: 'DshConversationHubScreen',
    screenKind: 'FLOW_STEP',
    flowId: 'dsh.support.chat',
    requiredStates: ['loading', 'error', 'success', 'retry', 'blocked'],
    analytics: { screenView: 'client_dsh_conversation_workspace_view' },
    fallbackRouteId: 'dsh-orders',
    releaseCriticality: 'P1',
    status: 'VERIFIED',
  },
  {
    screenId: 'client.dsh.listing.status-update',
    routeId: 'dsh-listing-status-update',
    surfaceId: 'app-client',
    ownerKind: 'service',
    ownerId: 'dsh',
    serviceId: 'dsh',
    ownerPath: 'dsh/frontend/app-client/screens/OperationScreens.tsx',
    componentName: 'DshListingStatusUpdateScreen',
    screenKind: 'FLOW_STEP',
    flowId: 'dsh.operations.listing',
    requiredStates: ['loading', 'error', 'success', 'retry', 'blocked'],
    analytics: { screenView: 'client_dsh_listing_status_update_view' },
    fallbackRouteId: 'dsh-home',
    releaseCriticality: 'P2',
    status: 'VERIFIED',
  },
  {
    screenId: 'client.dsh.order.issue.workspace',
    routeId: 'dsh-order-issue-workspace',
    surfaceId: 'app-client',
    ownerKind: 'service',
    ownerId: 'dsh',
    serviceId: 'dsh',
    ownerPath: 'dsh/frontend/app-client/screens/OperationScreens.tsx',
    componentName: 'DshOrderIssueHubScreen',
    screenKind: 'FLOW_STEP',
    flowId: 'dsh.support.issue',
    requiredStates: ['loading', 'error', 'success', 'retry', 'blocked'],
    analytics: { screenView: 'client_dsh_order_issue_workspace_view' },
    fallbackRouteId: 'dsh-orders',
    releaseCriticality: 'P1',
    status: 'VERIFIED',
  },
  {
    screenId: 'client.dsh.proxy.workspace',
    routeId: 'dsh-proxy-workspace',
    surfaceId: 'app-client',
    ownerKind: 'service',
    ownerId: 'dsh',
    serviceId: 'dsh',
    ownerPath: 'dsh/frontend/app-client/screens/OperationScreens.tsx',
    componentName: 'DshProxyHubScreen',
    screenKind: 'FLOW_STEP',
    flowId: 'dsh.proxy',
    requiredStates: ['loading', 'error', 'success', 'retry', 'blocked'],
    analytics: { screenView: 'client_dsh_proxy_workspace_view' },
    fallbackRouteId: 'dsh-orders',
    releaseCriticality: 'P2',
    status: 'VERIFIED',
  },
  {
    screenId: 'client.dsh.service.settings',
    routeId: 'dsh-service-settings',
    surfaceId: 'app-client',
    ownerKind: 'service',
    ownerId: 'dsh',
    serviceId: 'dsh',
    ownerPath: 'dsh/frontend/app-client/screens/OperationScreens.tsx',
    componentName: 'DshServiceSettingsHubScreen',
    screenKind: 'FLOW_STEP',
    flowId: 'dsh.service-settings',
    requiredStates: ['loading', 'error', 'success', 'retry', 'blocked'],
    analytics: { screenView: 'client_dsh_service_settings_view' },
    fallbackRouteId: 'dsh-home',
    releaseCriticality: 'P2',
    status: 'VERIFIED',
  },
  {
    screenId: 'client.dsh.zone.set',
    routeId: 'dsh-zone-set',
    surfaceId: 'app-client',
    ownerKind: 'service',
    ownerId: 'dsh',
    serviceId: 'dsh',
    ownerPath: 'dsh/frontend/app-client/screens/OperationScreens.tsx',
    componentName: 'DshZoneSetScreen',
    screenKind: 'FLOW_STEP',
    flowId: 'dsh.service-zone',
    requiredStates: ['loading', 'error', 'success', 'retry', 'blocked'],
    analytics: { screenView: 'client_dsh_zone_set_view' },
    fallbackRouteId: 'dsh-home',
    releaseCriticality: 'P2',
    status: 'VERIFIED',
  },
  {
    screenId: 'client.dsh.orders.history',
    routeId: 'dsh-orders',
    surfaceId: 'app-client',
    ownerKind: 'service',
    ownerId: 'dsh',
    serviceId: 'dsh',
    ownerPath: 'dsh/frontend/app-client/screens/OrdersTrackingScreens.tsx',
    componentName: 'DshOrdersListScreen',
    screenKind: 'SCREEN_ENTRY',
    flowId: 'dsh.orders',
    requiredStates: ['loading', 'empty', 'error', 'success', 'offline'],
    analytics: { screenView: 'client_dsh_orders_history_view' },
    deepLinkPath: '/dsh/orders',
    fallbackRouteId: 'dsh-home',
    releaseCriticality: 'P0',
    status: 'VERIFIED',
  },
  {
    screenId: 'client.dsh.order.smart-followup',
    routeId: 'dsh-tracking',
    surfaceId: 'app-client',
    ownerKind: 'service',
    ownerId: 'dsh',
    serviceId: 'dsh',
    ownerPath: 'dsh/frontend/app-client/screens/OrdersTrackingScreens.tsx',
    componentName: 'DshTrackingScreen',
    screenKind: 'FLOW_STEP',
    flowId: 'dsh.tracking',
    requiredStates: ['loading', 'error', 'success', 'offline', 'retry', 'blocked'],
    analytics: { screenView: 'client_dsh_order_smart_followup_view' },
    deepLinkPath: '/dsh/orders/:orderId/tracking',
    fallbackRouteId: 'dsh-orders',
    releaseCriticality: 'P0',
    status: 'VERIFIED',
  },
  {
    screenId: 'client.dsh.order.rating',
    routeId: 'dsh-order-rating',
    surfaceId: 'app-client',
    ownerKind: 'service',
    ownerId: 'dsh',
    serviceId: 'dsh',
    ownerPath: 'dsh/frontend/app-client/screens/DshRatingScreen.tsx',
    componentName: 'DshRatingScreen',
    screenKind: 'FLOW_STEP',
    flowId: 'dsh.orders',
    requiredStates: ['loading', 'error', 'success', 'retry', 'cancelled'],
    analytics: { screenView: 'client_dsh_order_rating_view' },
    fallbackRouteId: 'dsh-orders',
    releaseCriticality: 'P2',
    status: 'READY_FOR_REVIEW',
  },
  {
    screenId: 'client.dsh.checkout.intent',
    routeId: 'dsh-checkout-intent',
    surfaceId: 'app-client',
    ownerKind: 'service',
    ownerId: 'dsh',
    serviceId: 'dsh',
    ownerPath: 'dsh/frontend/app-client/screens/DshCheckoutIntentScreen.tsx',
    componentName: 'DshCheckoutIntentScreen',
    screenKind: 'FLOW_STEP',
    flowId: 'dsh.checkout',
    requiredStates: ['loading', 'error', 'blocked', 'retry'],
    analytics: { screenView: 'client_dsh_checkout_intent_view' },
    fallbackRouteId: 'dsh-cart',
    releaseCriticality: 'P0',
    status: 'READY_FOR_REVIEW',
  },
  {
    screenId: 'client.dsh.wallet.hub',
    routeId: 'dsh-wallet',
    surfaceId: 'app-client',
    ownerKind: 'service',
    ownerId: 'dsh',
    serviceId: 'dsh',
    ownerPath: 'dsh/frontend/app-client/screens/MySpaceSubScreens.tsx',
    componentName: 'DshWalletHubScreen',
    screenKind: 'SCREEN_ENTRY',
    flowId: 'dsh.wallet',
    requiredStates: ['loading', 'empty', 'error', 'success', 'offline', 'disabled'],
    analytics: { screenView: 'client_dsh_wallet_hub_view' },
    fallbackRouteId: 'dsh-my-space',
    releaseCriticality: 'P1',
    status: 'VERIFIED',
  },
  {
    screenId: 'client.dsh.loyalty.hub',
    routeId: 'dsh-loyalty',
    surfaceId: 'app-client',
    ownerKind: 'service',
    ownerId: 'dsh',
    serviceId: 'dsh',
    ownerPath: 'dsh/frontend/app-client/screens/MySpaceSubScreens.tsx',
    componentName: 'DshLoyaltyHubScreen',
    screenKind: 'SCREEN_ENTRY',
    flowId: 'dsh.loyalty',
    requiredStates: ['loading', 'empty', 'error', 'success', 'offline', 'disabled'],
    analytics: { screenView: 'client_dsh_loyalty_hub_view' },
    fallbackRouteId: 'dsh-my-space',
    releaseCriticality: 'P1',
    status: 'VERIFIED',
  },
  {
    screenId: 'client.dsh.subscriptions.hub',
    routeId: 'dsh-subscriptions',
    surfaceId: 'app-client',
    ownerKind: 'service',
    ownerId: 'dsh',
    serviceId: 'dsh',
    ownerPath: 'dsh/frontend/app-client/screens/MySpaceSubScreens.tsx',
    componentName: 'DshSubscriptionsHubScreen',
    screenKind: 'SCREEN_ENTRY',
    flowId: 'dsh.subscriptions',
    requiredStates: ['loading', 'empty', 'error', 'success', 'offline', 'disabled'],
    analytics: { screenView: 'client_dsh_subscriptions_hub_view' },
    fallbackRouteId: 'dsh-my-space',
    releaseCriticality: 'P1',
    status: 'VERIFIED',
  },
  {
    screenId: 'client.dsh.addresses.hub',
    routeId: 'dsh-addresses',
    surfaceId: 'app-client',
    ownerKind: 'service',
    ownerId: 'dsh',
    serviceId: 'dsh',
    ownerPath: 'dsh/frontend/app-client/screens/MySpaceSubScreens.tsx',
    componentName: 'DshAddressesHubScreen',
    screenKind: 'SCREEN_ENTRY',
    flowId: 'dsh.addresses',
    requiredStates: ['loading', 'empty', 'error', 'success', 'offline', 'disabled'],
    analytics: { screenView: 'client_dsh_addresses_hub_view' },
    fallbackRouteId: 'dsh-my-space',
    releaseCriticality: 'P1',
    status: 'VERIFIED',
  },
  {
    screenId: 'client.dsh.location.hub',
    routeId: 'dsh-location',
    surfaceId: 'app-client',
    ownerKind: 'service',
    ownerId: 'dsh',
    serviceId: 'dsh',
    ownerPath: 'dsh/frontend/app-client/screens/MySpaceSubScreens.tsx',
    componentName: 'DshLocationHubScreen',
    screenKind: 'SCREEN_ENTRY',
    flowId: 'dsh.location',
    requiredStates: ['loading', 'empty', 'error', 'success', 'offline', 'disabled'],
    analytics: { screenView: 'client_dsh_location_hub_view' },
    fallbackRouteId: 'dsh-my-space',
    releaseCriticality: 'P1',
    status: 'VERIFIED',
  },
  {
    screenId: 'client.dsh.identity.hub',
    routeId: 'dsh-identity',
    surfaceId: 'app-client',
    ownerKind: 'service',
    ownerId: 'dsh',
    serviceId: 'dsh',
    ownerPath: 'dsh/frontend/app-client/screens/MySpaceSubScreens.tsx',
    componentName: 'DshIdentityHubScreen',
    screenKind: 'SCREEN_ENTRY',
    flowId: 'dsh.identity',
    requiredStates: ['loading', 'empty', 'error', 'success', 'offline', 'disabled'],
    analytics: { screenView: 'client_dsh_identity_hub_view' },
    fallbackRouteId: 'dsh-my-space',
    releaseCriticality: 'P1',
    status: 'VERIFIED',
  },
  {
    screenId: 'client.dsh.commercial.hub',
    routeId: 'dsh-commercial',
    surfaceId: 'app-client',
    ownerKind: 'service',
    ownerId: 'dsh',
    serviceId: 'dsh',
    ownerPath: 'dsh/frontend/app-client/screens/MySpaceSubScreens.tsx',
    componentName: 'DshCommercialHubScreen',
    screenKind: 'SCREEN_ENTRY',
    flowId: 'dsh.commercial',
    requiredStates: ['loading', 'empty', 'error', 'success', 'offline', 'disabled'],
    analytics: { screenView: 'client_dsh_commercial_hub_view' },
    fallbackRouteId: 'dsh-my-space',
    releaseCriticality: 'P1',
    status: 'VERIFIED',
  },
  {
    screenId: 'client.dsh.appearance.hub',
    routeId: 'dsh-appearance',
    surfaceId: 'app-client',
    ownerKind: 'service',
    ownerId: 'dsh',
    serviceId: 'dsh',
    ownerPath: 'dsh/frontend/app-client/screens/MySpaceSubScreens.tsx',
    componentName: 'DshAppearanceHubScreen',
    screenKind: 'SCREEN_ENTRY',
    flowId: 'dsh.appearance',
    requiredStates: ['loading', 'empty', 'error', 'success', 'offline', 'disabled'],
    analytics: { screenView: 'client_dsh_appearance_hub_view' },
    fallbackRouteId: 'dsh-my-space',
    releaseCriticality: 'P1',
    status: 'VERIFIED',
  },
  {
    screenId: 'client.dsh.preferences.hub',
    routeId: 'dsh-preferences',
    surfaceId: 'app-client',
    ownerKind: 'service',
    ownerId: 'dsh',
    serviceId: 'dsh',
    ownerPath: 'dsh/frontend/app-client/screens/MySpaceSubScreens.tsx',
    componentName: 'DshPreferencesHubScreen',
    screenKind: 'SCREEN_ENTRY',
    flowId: 'dsh.preferences',
    requiredStates: ['loading', 'empty', 'error', 'success', 'offline', 'disabled'],
    analytics: { screenView: 'client_dsh_preferences_hub_view' },
    fallbackRouteId: 'dsh-my-space',
    releaseCriticality: 'P1',
    status: 'VERIFIED',
  },
] as const satisfies readonly DshClientScreenRegistryItem[];
