import { ServiceRecord } from './services.types';

export const PREVIEW_SERVICE_RECORDS: readonly ServiceRecord[] = [
  {
    id: 'service-dsh-delivery',
    label: 'DSH Delivery',
    description: 'تفعيل وإدارة خدمة التوصيل لتطبيق العميل والشريك والكابتن.',
    owner: 'Platform',
    status: 'live',
    clientVisibility: 'visible',
    scope: 'Global',
    risk: 'high',
    effectSummary: 'الخدمة مفعلة عالميًا وظاهرة للعملاء.',
    auditRollbackHint: 'الرجوع إلى وضع internal-only يتطلب موافقة المنصة.',
    reason: 'خدمة أساسية للمنصة',
    evidence: 'Platform Approval #001',
    rollbackTarget: 'internal-only',
  },
  {
    id: 'service-awnak',
    label: 'عونك',
    description: 'خدمة المساعدة وتوصيل الطلبات الخاصة للعملاء.',
    owner: 'Platform',
    status: 'live',
    clientVisibility: 'visible',
    scope: 'Global',
    risk: 'high',
    effectSummary: 'الخدمة مفعلة عالميًا وظاهرة للعملاء.',
    auditRollbackHint: 'الإيقاف يؤثر على عملاء عونك الحاليين.',
    reason: 'خدمة استراتيجية',
    evidence: 'Platform Approval #002',
    rollbackTarget: 'paused',
  },
  {
    id: 'service-shein',
    label: 'شي إن',
    description: 'خدمة التوصيل الخاصة لطلبات شي إن (Shein).',
    owner: 'Platform',
    status: 'pilot',
    clientVisibility: 'visible',
    scope: 'City',
    risk: 'medium',
    effectSummary: 'الخدمة في وضع تجريبي لمدن محددة فقط.',
    auditRollbackHint: 'التراجع إلى internal-only عند أي مشكلة تشغيلية.',
    reason: 'إطلاق تجريبي',
    evidence: 'Pilot Plan #City-01',
    rollbackTarget: 'internal-only',
  },
  {
    id: 'service-store-pickup',
    label: 'Store Pickup',
    description: 'خدمة الاستلام من الفرع بدون توصيل.',
    owner: 'Platform',
    status: 'internal-only',
    clientVisibility: 'hidden',
    scope: 'Global',
    risk: 'low',
    effectSummary: 'الخدمة مفعلة للموظفين فقط ولم تظهر للعملاء بعد.',
    auditRollbackHint: 'يمكن التراجع للإيقاف بأمان.',
    reason: 'اختبار داخلي',
    evidence: 'QA Test Run #994',
    rollbackTarget: 'paused',
  },
  {
    id: 'service-scheduled-orders',
    label: 'Scheduled Orders',
    description: 'السماح للعملاء بجدولة طلبات التوصيل مسبقًا.',
    owner: 'Platform',
    status: 'pilot',
    clientVisibility: 'visible',
    scope: 'City',
    risk: 'medium',
    effectSummary: 'الخدمة في وضع تجريبي لمدن محددة فقط.',
    auditRollbackHint: 'التراجع إلى internal-only متاح بأمان.',
    reason: 'اختبار قابلية التوسع',
    evidence: 'Pilot Plan #City-02',
    rollbackTarget: 'internal-only',
  },
];
