export const surfaceCatalog = [
  'entry',
  'tasks-inbox',
  'task-detail',
  'support-directory',
  'chat-read-ack',
  'chat-send',
  'cod-balance',
  'job-reject',
  'order-accept',
  'order-deliver',
  'order-details',
  'order-get',
  'order-pickup',
  'orders-list',
  'orders-offers-list',
  'profile-get',
  'proof-upload',
  'tier-evaluate',
  'tier-info',
  '_flow-id_'
] as const;
