/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/stores": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List discovery stores
         * @description Retrieve a list of stores that pass the shared visibility/serviceability gates, with optional category and search query filters.
         */
        get: operations["listDiscoveryStores"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        DiscoveryStoresResponse: {
            stores: components["schemas"]["DiscoveryStore"][];
            pagination: {
                limit: number;
                offset: number;
                total: number;
            };
        };
        DiscoveryStore: {
            id: string;
            name: string;
            address: string;
            category_id?: string;
            image_url?: string;
            logo_image_url?: string;
            rating?: number;
            distance_label: string;
            delivery_label: string;
            service_label: string;
            status_label: string;
            /** @enum {string} */
            status_tone: "open" | "closed";
            has_offer: boolean;
            offer_label?: string;
            publish_stage: string;
        };
        ErrorResponse: {
            code: string;
            message: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listDiscoveryStores: {
        parameters: {
            query?: {
                /** @description Filter stores by category ID */
                category_id?: string;
                /** @description Search term to filter stores by name, address, etc. */
                query?: string;
                /** @description Filter mode for discovery feed */
                filter?: "all" | "favorites" | "nearest" | "new" | "offers";
                /** @description Maximum number of stores to return */
                limit?: number;
                /** @description Number of stores to skip */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiscoveryStoresResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
