INSERT INTO dsh_store_discovery_stores (
  id,
  name,
  address,
  category_id,
  image_url,
  logo_image_url,
  rating,
  distance_label,
  delivery_label,
  service_label,
  status_label,
  status_tone,
  has_offer,
  offer_label,
  publish_stage,
  supports_pickup,
  supports_partner_delivery,
  search_text,
  partner_readiness_status,
  catalog_quality_status,
  catalog_pricing_status,
  marketing_visibility_status
) VALUES
  (
    'store-1001',
    'Haddah Central Market',
    'Haddah Street, Sanaa',
    'grocery',
    'dsh.store.haddah.cover.v1',
    'dsh.store.haddah.logo.v1',
    4.80,
    '2.1 km',
    'BThwani delivery',
    'Open for delivery',
    'Open',
    'open',
    TRUE,
    'Fresh produce offer',
    'published',
    TRUE,
    TRUE,
    'grocery fresh market haddah offer',
    'ready',
    'approved',
    'approved',
    'active'
  ),
  (
    'store-1002',
    'Al Sabeen Bakery',
    'Al Sabeen District',
    'bakery',
    'dsh.store.sabeen.cover.v1',
    'dsh.store.sabeen.logo.v1',
    4.60,
    '3.4 km',
    'Partner delivery',
    'Ready today',
    'Open',
    'open',
    FALSE,
    NULL,
    'published',
    TRUE,
    TRUE,
    'bakery bread sabeen',
    'ready',
    'approved',
    'approved',
    'active'
  ),
  (
    'store-1003',
    'Tahrir Mini Store',
    'Tahrir Square',
    'grocery',
    'dsh.store.tahrir.cover.v1',
    'dsh.store.tahrir.logo.v1',
    4.40,
    '1.2 km',
    'Pickup available',
    'Pickup only',
    'Open',
    'open',
    TRUE,
    'Pickup discount',
    'published',
    TRUE,
    FALSE,
    'grocery pickup tahrir offer',
    'ready',
    'approved',
    'approved',
    'active'
  ),
  (
    'store-1004',
    'Shumaila Evening Mart',
    'Shumaila Main Road',
    'convenience',
    'dsh.store.shumaila.cover.v1',
    'dsh.store.shumaila.logo.v1',
    4.20,
    '5.0 km',
    'BThwani delivery',
    'Closed now',
    'Closed',
    'closed',
    FALSE,
    NULL,
    'published',
    TRUE,
    TRUE,
    'convenience shumaila evening',
    'ready',
    'approved',
    'approved',
    'active'
  )
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  address = EXCLUDED.address,
  category_id = EXCLUDED.category_id,
  image_url = EXCLUDED.image_url,
  logo_image_url = EXCLUDED.logo_image_url,
  rating = EXCLUDED.rating,
  distance_label = EXCLUDED.distance_label,
  delivery_label = EXCLUDED.delivery_label,
  service_label = EXCLUDED.service_label,
  status_label = EXCLUDED.status_label,
  status_tone = EXCLUDED.status_tone,
  has_offer = EXCLUDED.has_offer,
  offer_label = EXCLUDED.offer_label,
  publish_stage = EXCLUDED.publish_stage,
  supports_pickup = EXCLUDED.supports_pickup,
  supports_partner_delivery = EXCLUDED.supports_partner_delivery,
  search_text = EXCLUDED.search_text,
  partner_readiness_status = EXCLUDED.partner_readiness_status,
  catalog_quality_status = EXCLUDED.catalog_quality_status,
  catalog_pricing_status = EXCLUDED.catalog_pricing_status,
  marketing_visibility_status = EXCLUDED.marketing_visibility_status,
  visibility_updated_at = NOW(),
  updated_at = NOW();
