import type {
  DshPlatformAuditEntry,
  DshPlatformProviderControlRecord,
  DshPlatformScopeLayer,
  DshPlatformSimulationScenario,
  DshPlatformVarRecord,
} from './vars.types';

export const DSH_PLATFORM_OPERATIONAL_VARS: readonly DshPlatformVarRecord[] = [
  {
    id: 'dispatch-zone-capacity',
    key: 'dsh.dispatch.assignment.maxConcurrentOrders',
    label: 'حد الإسناد المتزامن للمنطقة',
    owner: 'DSH',
    status: 'ready-for-binding',
    scope: 'Zone',
    risk: 'medium',
    currentPreviewValue: '18 طلبًا متزامنًا لكل Zone',
    proposedPreviewValue: '22 طلبًا متزامنًا لسيناريو الذروة المسائية',
    effectSummary: 'يوسع سعة الإسناد في المناطق الحضرية قبل الدخول في ازدحام اليد العاملة.',
    auditRollbackHint: 'احتفظ بآخر snapshot للـ zone قبل أي اعتماد، ثم أعده إذا ارتفع زمن الالتقاط فوق العتبة.',
    precedenceNote: 'إعداد Zone يتقدم على City وRegion عندما تتكرر نفس السياسة التشغيلية.',
  },
  {
    id: 'pickup-sla-buffer',
    key: 'dsh.sla.pickup.bufferMinutes',
    label: 'هامش SLA للاستلام',
    owner: 'DSH',
    status: 'preview-only',
    scope: 'Service',
    risk: 'low',
    currentPreviewValue: '7 دقائق كحزام أمان موحد للخدمة',
    proposedPreviewValue: '5 دقائق لمسار الطلبات السريعة فقط',
    effectSummary: 'يقلل التأخير المسموح قبل التصعيد ويشدد مراقبة الالتقاط السريع.',
    auditRollbackHint: 'ارجع إلى baseline الخدمة إذا زادت تنبيهات الدعم أو انخفضت جاهزية الكباتن.',
    precedenceNote: 'Service يحدد baseline، ثم تُطبّق overrides الأدق تحت نفس المالك.',
  },
  {
    id: 'awnak-city-readiness',
    key: 'dsh.readiness.awnak.cityMode',
    label: 'وضع جاهزية عونك على مستوى المدينة',
    owner: 'DSH',
    status: 'contract-needed',
    scope: 'City',
    risk: 'high',
    currentPreviewValue: 'manual-check في المدن الجديدة',
    proposedPreviewValue: 'semi-automatic gate عند تحقق الكثافة والتغطية',
    effectSummary: 'ينقل عونك من تفعيل يدوي كامل إلى بوابة readiness شبه آلية وفق معايير التشغيل.',
    auditRollbackHint: 'إذا هبطت تغطية الخدمة أو تعثرت التخصيصات، أعِد وضع المدينة إلى manual-check.',
    precedenceNote: 'City override يقيّد أي Region baseline عندما يخص جاهزية عونك محليًا.',
  },
  {
    id: 'region-rebalance-threshold',
    key: 'dsh.geo.rebalance.threshold',
    label: 'عتبة إعادة توازن المناطق',
    owner: 'DSH',
    status: 'ready-for-binding',
    scope: 'Region',
    risk: 'medium',
    currentPreviewValue: 'فرق 14% بين العرض والطلب قبل trigger',
    proposedPreviewValue: 'فرق 10% في المناطق سريعة الدوران',
    effectSummary: 'يسرّع اكتشاف الاختلالات الإقليمية قبل تضخم الاختناق التشغيلي.',
    auditRollbackHint: 'ثبّت regional snapshot مع heatmap baseline ثم ارجع إليه إذا زادت التحويلات اليدوية.',
    precedenceNote: 'Region يحدد سلوك التوازن قبل أن تتدخل City وZone لتخصيص الانحرافات.',
  },
  {
    id: 'shein-delivery-pattern',
    key: 'dsh.delivery.pattern.sheinProxyWindow',
    label: 'نافذة تشغيل شي إن كمسار توصيل',
    owner: 'DSH',
    status: 'contract-needed',
    scope: 'Category',
    risk: 'high',
    currentPreviewValue: 'proxy-search من 09:00 إلى 23:00 لفئة الأزياء',
    proposedPreviewValue: '24/7 لفئات الأزياء ذات الطلب المرتفع فقط',
    effectSummary: 'يوسع مسار شي إن تشغيليًا بدون منح أي ملكية مالية خارج WLT.',
    auditRollbackHint: 'أغلق التوسعة إلى النافذة الأصلية إذا زادت طلبات fallback اليدوي أو تباطأت الموافقات.',
    precedenceNote: 'Category يعلو على Service عندما يكون نمط التوصيل مخصصًا لفئة بعينها.',
  },
  {
    id: 'store-captain-coverage',
    key: 'dsh.store.readiness.minimumCaptainCoverage',
    label: 'الحد الأدنى لتغطية الكباتن على مستوى المتجر',
    owner: 'DSH',
    status: 'preview-only',
    scope: 'Store',
    risk: 'medium',
    currentPreviewValue: '2 كابتن كحد أدنى للمتاجر الحيوية',
    proposedPreviewValue: '3 كباتن في المتاجر ذات الذروة المركبة',
    effectSummary: 'يرفع استعداد المتجر قبل تحويله إلى وضع readiness عالي الكثافة.',
    auditRollbackHint: 'ارجع للحد الأدنى الحالي إذا ارتفعت ساعات الخمول أو انخفض معدل الامتلاء.',
    precedenceNote: 'Store هو آخر طبقة precedence ويكسر أي baseline أوسع عند الحاجة المحلية.',
  },
] as const;

export const DSH_PLATFORM_WLT_FINANCIAL_BRIDGE_VARS: readonly DshPlatformVarRecord[] = [
  {
    id: 'delivery-base-fee',
    key: 'wlt.fees.delivery.baseFeeYER',
    label: 'رسم التوصيل الأساسي',
    owner: 'WLT',
    status: 'contract-needed',
    scope: 'City',
    risk: 'financial',
    currentPreviewValue: '2,200 YER كمعاينة عرض فقط',
    proposedPreviewValue: '2,500 YER في محاكاة موسم الذروة',
    effectSummary: 'يعكس تأثير الرسوم على قرار الإطلاق، بينما تبقى الحقيقة المالية وعقودها داخل WLT.',
    auditRollbackHint: 'لا rollback مالي من DSH؛ فقط ارجع العرض preview إلى baseline المعروض من WLT.',
    precedenceNote: 'DSH يقرأ bridge city-level، لكن WLT يبقى صاحب source-of-truth لكل مستوى مالي.',
  },
  {
    id: 'platform-commission-rate',
    key: 'wlt.commission.platformRate',
    label: 'نسبة عمولة المنصة',
    owner: 'WLT',
    status: 'ready-for-binding',
    scope: 'Category',
    risk: 'financial',
    currentPreviewValue: '12% لفئة الإلكترونيات',
    proposedPreviewValue: '13% لفئة الإلكترونيات عالية الهامش',
    effectSummary: 'يبيّن كيف تتبدل قراءة الربحية داخل DSH بدون نقل الملكية المالية من WLT.',
    auditRollbackHint: 'أي rollback هنا يعني إعادة قراءة preview من عقد WLT المعتمد، لا تطبيق محلي من DSH.',
    precedenceNote: 'Category commission لا تُعتمد داخل DSH؛ فقط تُعرض بترتيبها القادم من WLT.',
  },
  {
    id: 'cod-reserve-floor',
    key: 'wlt.cod.reserve.floor',
    label: 'حد الرصيد الضامن لـ COD',
    owner: 'WLT',
    status: 'preview-only',
    scope: 'Region',
    risk: 'financial',
    currentPreviewValue: '150,000 YER كأرضية ضمان إقليمية',
    proposedPreviewValue: '175,000 YER لمناطق المخاطر المرتفعة',
    effectSummary: 'يكشف أثر تشديد الضمان على تغطية المناطق، لكن القرار المالي يبقى لدى WLT فقط.',
    auditRollbackHint: 'استرجاع baseline الضامن يتم من WLT ledger reference وليس من شاشة Platform.',
    precedenceNote: 'Region floor يصل كجسر مرئي؛ DSH لا يملك كسره أو إعادة ترتيبه.',
  },
  {
    id: 'refund-auto-approval-cap',
    key: 'wlt.refunds.autoApprovalCap',
    label: 'حد الاسترداد الآلي',
    owner: 'WLT',
    status: 'contract-needed',
    scope: 'Global',
    risk: 'financial',
    currentPreviewValue: '8,000 YER للحد الآلي العالمي',
    proposedPreviewValue: '5,000 YER لمسار تجريبي أكثر تحفظًا',
    effectSummary: 'يوضح كيف يتغير مسار الدعم والتصعيد عند خفض سقف الموافقة الآلية.',
    auditRollbackHint: 'الرجوع هنا يعني إعادة سقف WLT baseline وإخفاء السيناريو المقترح من منصة DSH.',
    precedenceNote: 'Global financial guard من WLT يهيمن على أي عرض تشغيلي لاحق داخل DSH.',
  },
  {
    id: 'partner-settlement-cycle',
    key: 'wlt.settlement.cycle.partner',
    label: 'دورة تسوية الشريك',
    owner: 'WLT',
    status: 'preview-only',
    scope: 'Service',
    risk: 'financial',
    currentPreviewValue: 'T+7 كمرجع تسوية للخدمة',
    proposedPreviewValue: 'T+5 لشركاء الخدمة عالية الجدارة',
    effectSummary: 'يعطي فريق Platform تصورًا زمنيًا لتأثير التسوية على التشغيل دون أي ادعاء truth محاسبي.',
    auditRollbackHint: 'العودة إلى T+7 تتم عبر عقد WLT المعروض وليس عبر زر داخل DSH.',
    precedenceNote: 'Service settlement cycle يُقرأ من WLT فقط ويُستخدم داخل DSH كإشارة قرار تشغيلية.',
  },
] as const;

export const DSH_PLATFORM_PROVIDER_CONTROL_VARS: readonly DshPlatformProviderControlRecord[] = [
  {
    id: 'provider-awnak-availability',
    key: 'provider.awnak.availability-sync',
    label: 'تحكم مزود عونك للتوفر',
    owner: 'Provider',
    status: 'preview-only',
    scope: 'City',
    risk: 'high',
    currentPreviewValue: 'priority=P1 · mode=active-passive',
    proposedPreviewValue: 'priority=P0 · mode=weighted-active',
    effectSummary: 'يحاكي تحسين توازن التوفر بين مزود عونك الرئيسي والاحتياطي داخل المدينة.',
    auditRollbackHint: 'اعتمد rollback target الظاهر فقط؛ لا يوجد تبديل فعلي في هذه المرحلة.',
    precedenceNote: 'City provider policy تظهر للعرض فقط، ولا تتحول إلى switch فعلي من شاشة Platform.',
    providerId: 'provider.awnak.v2',
    capability: 'availability-sync',
    priority: 'P1',
    fallback: 'provider.awnak.v1',
    mode: 'active-passive',
    testResult: 'آخر اختبار preview: أخضر على صنعاء مع fallback غير مفعّل.',
    rollbackTarget: 'provider.awnak.v1 snapshot',
  },
  {
    id: 'provider-shein-proxy',
    key: 'provider.shein.proxy-search',
    label: 'تحكم مزود شي إن للبحث الوكيل',
    owner: 'Provider',
    status: 'contract-needed',
    scope: 'Category',
    risk: 'high',
    currentPreviewValue: 'guarded mode مع escalation يدوي',
    proposedPreviewValue: 'guarded mode + auto-fallback بعد محاولتين',
    effectSummary: 'يرسم أثر تقليل الاحتكاك عند فشل البحث الوكيل في فئات الأزياء.',
    auditRollbackHint: 'إذا ارتفعت طلبات المراجعة، يُعرض rollback target فقط ولا يحدث تحويل فعلي.',
    precedenceNote: 'Category provider behavior يبقى preview-only حتى تثبت عقود المزود ومسار الاختبار.',
    providerId: 'provider.shein.proxy',
    capability: 'proxy-search',
    priority: 'P1',
    fallback: 'manual-review-lane',
    mode: 'guarded',
    testResult: 'آخر اختبار preview: أصفر، latency مرتفعة على طلبات mixed catalog.',
    rollbackTarget: 'manual-review-lane baseline',
  },
  {
    id: 'provider-dispatch-recovery',
    key: 'provider.dispatch.recovery-fallback',
    label: 'تحكم fallback لاستعادة الإسناد',
    owner: 'Provider',
    status: 'preview-only',
    scope: 'Zone',
    risk: 'medium',
    currentPreviewValue: 'shadow mode مع fallback إلى geo-heatmap-manual',
    proposedPreviewValue: 'shadow mode مع trigger أسرع عند اختناق Zone',
    effectSummary: 'يوضح كيف قد تتغير سرعة الاستجابة عند تعثر مسار الإسناد الآلي في الـ Zone.',
    auditRollbackHint: 'احتفظ بمسار geo-heatmap-manual كهدف rollback ظاهر فقط.',
    precedenceNote: 'Zone fallback preview يظل مرئيًا كاقتراح ولا يُنفذ من هذه الشاشة.',
    providerId: 'provider.dispatch.router',
    capability: 'fallback-routing',
    priority: 'P2',
    fallback: 'geo-heatmap-manual',
    mode: 'shadow',
    testResult: 'آخر اختبار preview: أخضر مع تحذير عن ازدحام نقطتين.',
    rollbackTarget: 'geo-heatmap-manual baseline',
  },
  {
    id: 'provider-zone-scoring',
    key: 'provider.geo.zone-score',
    label: 'تحكم مزود تقييم المناطق',
    owner: 'Provider',
    status: 'preview-only',
    scope: 'Subcategory',
    risk: 'medium',
    currentPreviewValue: 'regional default score',
    proposedPreviewValue: 'weighted score حسب subcategory حساسة زمنيًا',
    effectSummary: 'يعرض كيف يمكن أن تتغير أولوية المناطق لشرائح فرعية أكثر حساسية للزمن.',
    auditRollbackHint: 'الرجوع يتم إلى regional default score المعروض فقط.',
    precedenceNote: 'Subcategory تكسر Category عند العرض التحليلي، لكن دون تفعيل حقيقي.',
    providerId: 'provider.geo.zone-mapper',
    capability: 'zone-score',
    priority: 'P3',
    fallback: 'regional-default-map',
    mode: 'shadow',
    testResult: 'آخر اختبار preview: أخضر، فرق score ضمن 4%.',
    rollbackTarget: 'regional-default-map baseline',
  },
] as const;

export const DSH_PLATFORM_SCOPE_PRECEDENCE: readonly DshPlatformScopeLayer[] = [
  {
    id: 'scope-global',
    scope: 'Global',
    order: 1,
    title: 'Global baseline',
    description: 'الخط الأساسي الأعلى الذي يفرض guardrails العامة قبل أي تخصيص أدق.',
    ownerGuard: 'الحراس المالية العالمية تبقى لدى WLT، أما الحراس التشغيلية العامة فتبقى لدى DSH.',
    note: 'إذا تعارض Global مع طبقة أدق من المالك نفسه، تفوز الطبقة الأدق مع إبقاء guardrails العليا مرئية.',
  },
  {
    id: 'scope-service',
    scope: 'Service',
    order: 2,
    title: 'Service policy',
    description: 'تخصيص حسب الخدمة مثل DSH delivery أو Awnak readiness.',
    ownerGuard: 'DSH يملك الخدمة التشغيلية؛ WLT يملك أي خدمة ذات أثر مالي.',
    note: 'طبقة Service تُعد baseline مرنًا قبل Region وما دونها.',
  },
  {
    id: 'scope-region',
    scope: 'Region',
    order: 3,
    title: 'Regional control',
    description: 'ضبط كثافة التشغيل أو الضمان المالي بحسب الإقليم.',
    ownerGuard: 'الضبط الإقليمي المالي يعرض كجسر فقط إذا كان المصدر WLT.',
    note: 'Region يسبق City وZone ما لم يظهر override أدق من المالك نفسه.',
  },
  {
    id: 'scope-city',
    scope: 'City',
    order: 4,
    title: 'City override',
    description: 'طبقة تخص المدن ذات متطلبات readiness أو pricing مختلفة.',
    ownerGuard: 'يمكن لـ DSH عرضها تشغيليًا، لكن الماليات تظل WLT حتى في مستوى المدينة.',
    note: 'City يكسر Region في السياسات المحلية المؤكدة.',
  },
  {
    id: 'scope-zone',
    scope: 'Zone',
    order: 5,
    title: 'Zone pressure control',
    description: 'مناسب للإسناد والاختناق وإدارة الحمل الدقيق.',
    ownerGuard: 'DSH يملك zone operations؛ Provider control في هذا المستوى يبقى preview فقط.',
    note: 'Zone هو أقرب طبقة لتشغيل الإسناد الحي، لكنه هنا محاكاة فقط.',
  },
  {
    id: 'scope-category',
    scope: 'Category',
    order: 6,
    title: 'Category routing',
    description: 'تخصيصات متعلقة بنوع الخدمة أو العروض أو المسارات الخاصة.',
    ownerGuard: 'شي إن وأنماط التوصيل التشغيلية DSH-owned، أما أي عمولة أو رسوم فـ WLT-owned.',
    note: 'Category يكسر Service إذا كانت القاعدة مقصودة لفئة محددة.',
  },
  {
    id: 'scope-subcategory',
    scope: 'Subcategory',
    order: 7,
    title: 'Subcategory override',
    description: 'طبقة أدق لمتطلبات narrow routing أو provider preview scoring.',
    ownerGuard: 'تظهر كتحليل أدق لكنها لا تصبح binding بدون عقود مثبتة.',
    note: 'Subcategory يتقدم على Category عند تفعيل override أدق.',
  },
  {
    id: 'scope-store',
    scope: 'Store',
    order: 8,
    title: 'Store final override',
    description: 'آخر طبقة precedence وتلتقط التباينات المحلية للجاهزية والتغطية.',
    ownerGuard: 'DSH يملك readiness المحلي، لكن لا يملك أي ledger أو settlement local truth.',
    note: 'Store هو آخر كلمة تشغيلية ضمن حدود DSH preview الحالية.',
  },
] as const;

export const DSH_PLATFORM_SIMULATION_PREVIEW: readonly DshPlatformSimulationScenario[] = [
  {
    id: 'sim-peak-zone-capacity',
    title: 'محاكاة رفع سعة الإسناد في Zone الذروة',
    owner: 'DSH',
    scope: 'Zone',
    relatedKeys: [
      'dsh.dispatch.assignment.maxConcurrentOrders',
      'dsh.geo.rebalance.threshold',
    ],
    expectedImpact: 'زيادة throughput المتوقع مع تقليل الحاجة لتحويل يدوي في المناطق المكتظة.',
    guardrail: 'يجب ألا تتجاوز SLA الالتقاط baseline الحالي قبل أي انتقال لمرحلة binding.',
    blockedReason: 'UI/UX preview only: لا تطبيق مباشر ولا resolver فعلي في هذه المرحلة.',
  },
  {
    id: 'sim-wlt-fee-city',
    title: 'محاكاة تعديل رسم التوصيل عبر جسر WLT',
    owner: 'WLT',
    scope: 'City',
    relatedKeys: [
      'wlt.fees.delivery.baseFeeYER',
      'wlt.settlement.cycle.partner',
    ],
    expectedImpact: 'تغيير واضح في صورة الربحية والطلب المتوقع داخل منصة DSH فقط.',
    guardrail: 'أي أثر مالي حقيقي يحتاج اعتماد WLT ولا يخرج من preview bridge.',
    blockedReason: 'DSH لا يملك تطبيق الرسوم؛ الواجهة تعرض الأثر فقط.',
  },
  {
    id: 'sim-shein-provider-fallback',
    title: 'محاكاة fallback لمزود شي إن',
    owner: 'Provider',
    scope: 'Category',
    relatedKeys: ['provider.shein.proxy-search'],
    expectedImpact: 'تقليل المراجعات اليدوية المتوقعة عند فشل proxy-search المتكرر.',
    guardrail: 'يظل provider switching معطلاً حتى يثبت مسار الاختبار والعقد.',
    blockedReason: 'Provider control preview only: لا activate ولا switching فعلي.',
  },
  {
    id: 'sim-refund-cap-tightening',
    title: 'محاكاة خفض سقف الاسترداد الآلي',
    owner: 'WLT',
    scope: 'Global',
    relatedKeys: ['wlt.refunds.autoApprovalCap'],
    expectedImpact: 'زيادة التحويل إلى صف المراجعة مع خفض مخاطر الاسترداد التلقائي.',
    guardrail: 'القرار المالي والتنفيذي النهائي خارج DSH بالكامل.',
    blockedReason: 'تعرض الشاشة أثر الدعم والعمليات فقط، لا القرار المالي نفسه.',
  },
] as const;

export const DSH_PLATFORM_AUDIT_PREVIEW: readonly DshPlatformAuditEntry[] = [
  {
    id: 'audit-zone-capacity',
    title: 'Snapshot قبل تغيير سعة الإسناد',
    actor: 'DSH Platform reviewer',
    event: 'preview snapshot created',
    targetKey: 'dsh.dispatch.assignment.maxConcurrentOrders',
    stateLabel: 'طلب اعتماد',
    evidenceHint: 'التقط baseline للسعة وSLA والاختناقات قبل أي مرحلة binding.',
    rollbackHint: 'أعد baseline zone-capacity إذا ارتفع زمن الالتقاط أو زادت التحويلات اليدوية.',
  },
  {
    id: 'audit-wlt-fee-bridge',
    title: 'مراجعة جسر الرسوم المالية',
    actor: 'WLT finance owner',
    event: 'bridge comparison requested',
    targetKey: 'wlt.fees.delivery.baseFeeYER',
    stateLabel: 'مراجعة عقد',
    evidenceHint: 'قارن المعروض داخل DSH مع contract snapshot القادم من WLT.',
    rollbackHint: 'rollback هنا يعني إعادة العرض إلى current preview value الواردة من WLT.',
  },
  {
    id: 'audit-provider-fallback',
    title: 'تتبع fallback للمزود',
    actor: 'Provider operations reviewer',
    event: 'preview fallback audited',
    targetKey: 'provider.shein.proxy-search',
    stateLabel: 'preview-only',
    evidenceHint: 'احتفظ بنتيجة الاختبار الأخيرة وبالهدف الاحتياطي الظاهر قبل أي قرار لاحق.',
    rollbackHint: 'أعد target المزود إلى manual-review-lane إن ظهرت مخاطر latency أو mismatch.',
  },
  {
    id: 'audit-refund-cap',
    title: 'توثيق أثر سقف الاسترداد',
    actor: 'DSH support + WLT finance',
    event: 'impact preview captured',
    targetKey: 'wlt.refunds.autoApprovalCap',
    stateLabel: 'قرار مشترك',
    evidenceHint: 'سجل تأثير queue support وعدد الحالات المتوقع تحويلها للمراجعة.',
    rollbackHint: 'أعد العرض إلى baseline العالمي من WLT إذا ازدادت حمولة الدعم فوق الحد المخطط.',
  },
] as const;
